cy.on('uncaught:exception', (err, runnable) => {
    return false;
});
const { faker } = require('@faker-js/faker');
import server_page from "../pages/server_page";
import sidebar from "../pages/sidebar";
import configuration_page from "../pages/configuration_page";
import serverlist_page from "../pages/server-list_page";
import serverAction_page from "../pages/server-action_page";

describe('2.Create Server Tests Part1', () => {
    let configData;
    before(() => {
        cy.fixture('examples').then((data) => {
            configData = data;
        });
    })
    beforeEach(() => {
        cy.viewport(1920, 1080)
        cy.intercept('POST', `${configData.base_url}panel-main/api/v1/auth/sign-in`).as('signInRequest');
        cy.intercept('POST', `${configData.base_url}panel-main/api/panel/vm/prepare`).as('createServerRequest');
        cy.intercept('POST', `${configData.base_url}panel-main/api/panel/vm/resourceMetaData`).as('resourcePrices');
    })
    it('[PD-1] Add new server-1 (with backup and local net,HDD)', () => {
        const localIpName = faker.lorem.word()
        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        server_page.actions.clickCreateServerBtn()
        server_page.actions.checkCreateServerPageLbl()
        server_page.actions.selectServerOs(0)
        server_page.actions.selectVersionOs()
        server_page.actions.clickServerTitleField()
        server_page.actions.writeTitle(configData.test_server_with_backup)
        server_page.actions.writeDesc("with backup and local net,HDD")
        // server_page.actions.setCpu(2) // if resources are selected with buttons increment or decrement
        // server_page.actions.setRam(4)
        server_page.actions.writeCpuTxt(2)
        server_page.actions.writeRamTxt(4)
        server_page.actions.toggleBackupBtn()
        server_page.actions.writeBackupTitle("Test_Backup")
        server_page.actions.clickBackupCopiesBtn()
        server_page.actions.writeBackupCopiesTxt(2)
        server_page.actions.clickConfirmBackupCopyBtn()
        server_page.actions.selectBackupPeriod(2)
        server_page.actions.writeTimeSelector(0)
        server_page.actions.clickConfirmBackupBtn()
        server_page.actions.enableLocalIp()
        server_page.actions.clickLocalIpAddNewBtn()
        server_page.actions.writeLocalIpNameTxt(`Test_IP_${localIpName}`)
        server_page.actions.writeLocalIpAddressTxtforCustomOS("192.168.100.0")
        server_page.actions.writeLocalIpGatewayTxt("192.168.100.1")
        server_page.actions.clickLocalIpAddConfBtn()
        server_page.actions.clickLocalIpSelector()
        server_page.actions.selectLocalIpName(localIpName)
        server_page.actions.clickConfirmCreateServerBtn()
        server_page.actions.clickCloseModalBtn()
        server_page.actions.checkCreateApi(configData.test_server_with_backup)
        server_page.actions.isVisibleCreatedServer(configData.test_server_with_backup)

        serverlist_page.actions.searchServer(configData.test_server_with_backup)
        serverlist_page.actions.isVisibleSearchTxtServer(configData.test_server_with_backup)

        server_page.actions.checkElementTextPeriodically()

        serverlist_page.actions.clickServerCard(configData.test_server_with_backup)
        serverlist_page.actions.isVisibleServerDetail(configData.test_server_with_backup)
        serverAction_page.actions.isRunningServer()

    })
    it('[PD-10] Add new server-2 (without backup, with IP,SSD)', () => {
        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        server_page.actions.clickCreateServerBtn()
        server_page.actions.checkCreateServerPageLbl()
        server_page.actions.selectServerOs(0)
        server_page.actions.selectVersionOs()
        server_page.actions.writeTitle(configData.test_server_without_backup)
        server_page.actions.writeDesc("without backup, with IP,SSD")
        // server_page.actions.setCpu(2)
        // server_page.actions.setRam(4)
        server_page.actions.writeCpuTxt(2)
        server_page.actions.writeRamTxt(4)
        server_page.actions.clickDiskTypeSSDBtn()
        server_page.actions.setDisk(10)
        server_page.actions.enablePublicIp()
        server_page.actions.clickLoginTypeSSHBtn()
        server_page.actions.clickConfirmCreateServerBtn()
        server_page.actions.clickCloseModalBtn()
        server_page.actions.checkCreateApi(configData.test_server_without_backup)
        server_page.actions.isVisibleCreatedServer(configData.test_server_without_backup)

        serverlist_page.actions.searchServer(configData.test_server_without_backup)
        serverlist_page.actions.isVisibleSearchTxtServer(configData.test_server_without_backup)

        server_page.actions.checkElementTextPeriodically()

        serverlist_page.actions.clickServerCard(configData.test_server_without_backup)
        serverlist_page.actions.isVisibleServerDetail(configData.test_server_without_backup)
        serverAction_page.actions.isRunningServer()
    })
    it('[PD-11] Add new server-3 (with custom OS,NVME)', () => {
        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        server_page.actions.clickCreateServerBtn()
        server_page.actions.checkCreateServerPageLbl()
        server_page.actions.clickCustomOsTabBtn()
        server_page.actions.selectCustomOs(0)
        server_page.actions.clickServerTitleField()
        server_page.actions.writeTitle(configData.test_server_with_customOS)
        server_page.actions.writeDesc("with custom OS,NVME")
        // server_page.actions.setCpu(2) // with increment decrement buttons - for now no need
        // server_page.actions.setRam(4)
        server_page.actions.writeCpuTxt(2)
        server_page.actions.writeRamTxt(4)
        server_page.actions.clickDiskTypeNVMEBtn()
        server_page.actions.setDisk(10)
        server_page.actions.enablePublicIp()
        server_page.actions.clickConfirmCreateServerBtn()
        server_page.actions.clickCloseModalBtn()
        server_page.actions.checkCustomBMApi(configData.test_server_with_customOS)
        server_page.actions.isVisibleCreatedServer(configData.test_server_with_customOS)

        serverlist_page.actions.searchServer(configData.test_server_with_customOS)
        serverlist_page.actions.isVisibleSearchTxtServer(configData.test_server_with_customOS)

        server_page.actions.checkElementTextPeriodically()

        serverlist_page.actions.clickServerCard(configData.test_server_with_customOS)
        serverlist_page.actions.isVisibleServerDetail(configData.test_server_with_customOS)
        serverAction_page.actions.isRunningServer()
    })
    it('[PD-12] Mandatory fields validation', () => {
        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        server_page.actions.clickCreateServerBtn()
        server_page.actions.checkCreateServerPageLbl()
        server_page.actions.clickConfirmCreateServerBtn()
        // server_page.actions.isVisibleOsRequiredLbl()
        server_page.actions.isVisibleTitleRequiredLbl()
    })
    it('[PD-13] Add new server with invalid name (2 words)', () => {
        const serverName = faker.lorem.word() + " " + faker.lorem.word()
        const localIpName = faker.lorem.word()
        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        server_page.actions.clickCreateServerBtn()
        server_page.actions.checkCreateServerPageLbl()
        server_page.actions.clickCustomOsTabBtn()
        server_page.actions.selectCustomOs(0)
        server_page.actions.clickServerTitleField()
        server_page.actions.writeTitle(serverName)
        server_page.actions.writeDesc("Test Description about Server")
        // server_page.actions.setCpu(2)
        // server_page.actions.setRam(4)
        server_page.actions.writeCpuTxt(2)
        server_page.actions.writeRamTxt(4)
        server_page.actions.enableLocalIp()
        server_page.actions.clickLocalIpSelector()
        server_page.actions.selectLocalIpName(configData.test_local_ip)
        server_page.actions.clickLocalIpAddNewBtn()
        server_page.actions.writeLocalIpNameTxt(`Test_IP_${localIpName}`)
        server_page.actions.writeLocalIpAddressTxtforCustomOS("192.168.100.0")
        server_page.actions.writeLocalIpGatewayTxt("192.168.100.1")
        server_page.actions.clickLocalIpAddConfBtn()
        server_page.actions.clickConfirmCreateServerBtn()
        server_page.actions.checkTitleErrorLbl('Неверное название, только латинские буквы, цифры и символ "-".')
    })
    it('[PD-15] Add new server with invalid name (Cyrillic)', () => {
        const serverName = "ТестСервер"
        const localIpName = faker.lorem.word()
        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        server_page.actions.clickCreateServerBtn()
        server_page.actions.checkCreateServerPageLbl()
        server_page.actions.clickCustomOsTabBtn()
        server_page.actions.selectCustomOs(0)
        server_page.actions.clickServerTitleField()
        server_page.actions.writeTitle(serverName)
        server_page.actions.writeDesc("Test Description about Server")
        // server_page.actions.setCpu(2)
        // server_page.actions.setRam(4)
        server_page.actions.writeCpuTxt(2)
        server_page.actions.writeRamTxt(4)
        server_page.actions.enableLocalIp()
        server_page.actions.clickLocalIpSelector()
        server_page.actions.selectLocalIpName(configData.test_local_ip)
        server_page.actions.clickLocalIpAddNewBtn()
        server_page.actions.writeLocalIpNameTxt(`Test_IP_${localIpName}`)
        server_page.actions.writeLocalIpAddressTxtforCustomOS("192.168.100.0")
        server_page.actions.writeLocalIpGatewayTxt("192.168.100.1")
        server_page.actions.clickLocalIpAddConfBtn()
        server_page.actions.clickConfirmCreateServerBtn()
        server_page.actions.checkTitleErrorLbl('Неверное название, только латинские буквы, цифры и символ "-".')
    })
    it('[PD-16] Add new server with invalid name (symbols only)', () => {
        const serverName = faker.string.symbol()
        const localIpName = faker.lorem.word()
        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        server_page.actions.clickCreateServerBtn()
        server_page.actions.checkCreateServerPageLbl()
        server_page.actions.clickCustomOsTabBtn()
        server_page.actions.selectCustomOs(0)
        server_page.actions.clickServerTitleField()
        server_page.actions.writeTitle(serverName)
        server_page.actions.writeDesc("Test Description about Server")
        server_page.actions.writeCpuTxt(2)
        server_page.actions.writeRamTxt(4)
        server_page.actions.enableLocalIp()
        server_page.actions.clickLocalIpSelector()
        server_page.actions.selectLocalIpName(configData.test_local_ip)
        server_page.actions.clickLocalIpAddNewBtn()
        server_page.actions.writeLocalIpNameTxt(`Test_IP_${localIpName}`)
        server_page.actions.writeLocalIpAddressTxtforCustomOS("192.168.100.0")
        server_page.actions.writeLocalIpGatewayTxt("192.168.100.1")
        server_page.actions.clickLocalIpAddConfBtn()
        server_page.actions.clickConfirmCreateServerBtn()
        server_page.actions.checkTitleErrorLbl('Минимум 3 символа')
    })
    it('[PD-17] Add new server with invalid resources (CPU more than limit)', () => {
        const serverName = faker.lorem.word() + Math.round(Math.random() * 10000)

        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        server_page.actions.clickCreateServerBtn()
        server_page.actions.checkCreateServerPageLbl()
        server_page.actions.selectServerOs(0)
        server_page.actions.writeTitle(serverName)
        server_page.actions.writeDesc("Test Description about Server")
        server_page.actions.writeCpuTxt(2000)
        server_page.actions.isCpuIncreaseBtnDisabled()
    })
    it('[PD-18] Add new server with invalid resources (CPU negative number)', () => {
        const serverName = faker.lorem.word() + Math.round(Math.random() * 10000)

        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        server_page.actions.clickCreateServerBtn()
        server_page.actions.checkCreateServerPageLbl()
        server_page.actions.selectServerOs(0)
        server_page.actions.selectVersionOs()
        server_page.actions.writeTitle(serverName)
        server_page.actions.writeDesc("Test Description about Server")
        server_page.actions.writeCpuTxt(-1)
        server_page.actions.isCpuDescreaseBtnDisabled()
    })
    /*it('[PD-19] Add new server with invalid resources (CPU math symbols +/-)', () => {   //not actual as input fields for CPU was removed in new design
        const serverName = faker.lorem.word() + Math.round(Math.random() * 10000)

        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        server_page.actions.clickCreateServerBtn()
        server_page.actions.checkCreateServerPageLbl()
        server_page.actions.clickOsTxt()
        // server_page.actions.isOpenedModal()
        server_page.actions.selectServerOs(3)
        server_page.actions.clickConfirmOsBtn()
        cy.wait(2000)
        server_page.actions.writeTitle(serverName)
        server_page.actions.writeDesc("Test Description about Server")
        server_page.actions.writeCpuTxt("+")
        server_page.actions.checkCpuErrorLbl("Неверное значение")
    }) */
    it('[PD-20] Add new server with invalid resources (RAM more than limit)', () => {
        const serverName = faker.lorem.word() + Math.round(Math.random() * 10000)

        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        server_page.actions.clickCreateServerBtn()
        server_page.actions.checkCreateServerPageLbl()
        server_page.actions.selectServerOs(0)
        server_page.actions.selectVersionOs()
        server_page.actions.writeTitle(serverName)
        server_page.actions.writeDesc("Test Description about Server")
        server_page.actions.writeRamTxt(2000)
        server_page.actions.isRamIncreaseBtnDisabled()
    })
    it('[PD-21] Add new server with invalid resources (RAM negative number)', () => {
        const serverName = faker.lorem.word() + Math.round(Math.random() * 10000)

        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        server_page.actions.clickCreateServerBtn()
        server_page.actions.checkCreateServerPageLbl()
        server_page.actions.selectServerOs(0)
        server_page.actions.writeTitle(serverName)
        server_page.actions.writeDesc("Test Description about Server")
        server_page.actions.writeRamTxt(-1)
        server_page.actions.isRamDescreaseBtnDisabled()
    })
    /*it('[PD-22] Add new server with invalid resources (RAM math symbols +/-)', () => { //not actual as input fields for CPU was removed in new design
        const serverName = faker.lorem.word() + Math.round(Math.random() * 10000)

        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        server_page.actions.clickCreateServerBtn()
        server_page.actions.checkCreateServerPageLbl()
        server_page.actions.clickOsTxt()
        // server_page.actions.isOpenedModal()
        server_page.actions.selectServerOs(3)
        server_page.actions.clickConfirmOsBtn()
        cy.wait(2000)
        server_page.actions.writeTitle(serverName)
        server_page.actions.writeDesc("Test Description about Server")
        server_page.actions.writeCpuTxt(2)
        server_page.actions.writeRamTxt("+")
        server_page.actions.checkRamErrorLbl("Неверное значение")
    }) */
})
//Test-Server won't be touched here