cy.on('uncaught:exception', (err, runnable) => {
    return false;
});
const { faker } = require('@faker-js/faker');
import server_page from "../pages/server_page";
import sidebar from "../pages/sidebar";
import configuration_page from "../pages/configuration_page";
import serverlist_page from "../pages/server-list_page";
import serverAction_page from "../pages/server-action_page";

describe('3.Create Server Tests Part2', () => {
    let configData;
    before(() => {
        cy.fixture('examples').then((data) => {
            configData = data;
        });
    })
    beforeEach(() => {
        cy.viewport(1920, 1080)
        cy.intercept('POST', `${configData.base_url}panel-main/api/v1/auth/sign-in`).as('signInRequest');
        cy.intercept('POST', `${configData.base_url}panel-main/api/panel/vm/prepare`).as('createServerRequest');
        cy.intercept('POST', `${configData.base_url}panel-main/api/panel/vm/resourceMetaData`).as('resourcePrices');
    })
    it('[PD-111] Создать новый сервер с неправильными ресурсами (HDD Disk больше лимита)', () => {
        const serverName = faker.lorem.word() + Math.round(Math.random() * 10000)

        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        server_page.actions.clickCreateServerBtn()
        server_page.actions.checkCreateServerPageLbl()
        server_page.actions.clickOsTxt()
        server_page.actions.isOpenedModal()
        server_page.actions.selectServerOs(3)
        server_page.actions.clickConfirmOsBtn()
        cy.wait(5000)
        server_page.actions.clickServerTitleField()
        server_page.actions.writeTitle(serverName)
        server_page.actions.writeDesc("Test Description about Server")
        server_page.actions.writeCpuTxt(2)
        server_page.actions.writeRamTxt(4)
        server_page.actions.typeDiskSize(500000)
        server_page.actions.enablePublicIp()
        server_page.actions.isRedDiskTxt1()
    })
    it('[PD-112] Создать новый сервер с неправильными ресурсами (HDD Disk негативное число)', () => {
        const serverName = faker.lorem.word() + Math.round(Math.random() * 10000)

        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        server_page.actions.clickCreateServerBtn()
        server_page.actions.checkCreateServerPageLbl()
        server_page.actions.clickOsTxt()
        server_page.actions.isOpenedModal()
        server_page.actions.selectServerOs(3)
        server_page.actions.clickConfirmOsBtn()
        cy.wait(2000)
        server_page.actions.clickServerTitleField()
        server_page.actions.writeTitle(serverName)
        server_page.actions.writeDesc("Test Description about Server")
        server_page.actions.writeCpuTxt(2)
        server_page.actions.writeRamTxt(4)
        server_page.actions.typeDiskSize(-50)
        server_page.actions.enablePublicIp()
        server_page.actions.isRedDiskTxt1()
    })
    it('[PD-26] Создать новый сервер с неправильным называнием Бэкапа (кириллица)', () => {
        const serverName = faker.lorem.word() + Math.round(Math.random() * 10000)

        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        server_page.actions.clickCreateServerBtn()
        server_page.actions.checkCreateServerPageLbl()
        server_page.actions.clickOsTxt()
        server_page.actions.isOpenedModal()
        server_page.actions.selectServerOs(3)
        server_page.actions.clickConfirmOsBtn()
        cy.wait(4000)
        server_page.actions.clickServerTitleField()
        server_page.actions.writeTitle(serverName)
        server_page.actions.writeDesc("Test Description about Server")
        server_page.actions.writeCpuTxt(2)
        server_page.actions.writeRamTxt(4)
        server_page.actions.toggleBackupBtn()
        server_page.actions.isOpenedModal()
        server_page.actions.writeBackupTitle("Тест Бэкап")
        server_page.actions.clickBackupCopiesBtn()
        server_page.actions.writeBackupCopiesTxt(2)
        server_page.actions.clickConfirmBackupCopyBtn()
        server_page.actions.selectBackupPeriod(2)
        cy.wait(1000)
        server_page.actions.writeTimeSelector("00:00")
        server_page.actions.clickConfirmBackupBtn()
    })
    it('[PD-27] Создать новый сервер с неправильным названием расписания Бэкапа ( пустое значение )', () => {
        const serverName = faker.lorem.word() + Math.round(Math.random() * 10000)

        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        server_page.actions.clickCreateServerBtn()
        server_page.actions.checkCreateServerPageLbl()
        server_page.actions.clickOsTxt()
        server_page.actions.isOpenedModal()
        server_page.actions.selectServerOs(3)
        server_page.actions.clickConfirmOsBtn()
        cy.wait(4000)
        server_page.actions.clickServerTitleField()
        server_page.actions.writeTitle(serverName)
        server_page.actions.writeDesc("Test Description about Server")
        server_page.actions.writeCpuTxt(2)
        server_page.actions.writeRamTxt(4)
        server_page.actions.toggleBackupBtn()
        server_page.actions.isOpenedModal()
        server_page.actions.writeBackupTitle("  ")
        server_page.actions.clickBackupCopiesBtn()
        server_page.actions.writeBackupCopiesTxt(2)
        server_page.actions.clickConfirmBackupCopyBtn()
        server_page.actions.selectBackupPeriod(2)
        cy.wait(1000)
        server_page.actions.writeTimeSelector("00:00")
        server_page.actions.clickConfirmBackupBtn()
    })
    it('[PD-29] Создать новый сервер с 0 копией Бэкапа', () => {
        const serverName = faker.lorem.word() + Math.round(Math.random() * 10000)

        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        server_page.actions.clickCreateServerBtn()
        server_page.actions.checkCreateServerPageLbl()
        server_page.actions.clickOsTxt()
        server_page.actions.isOpenedModal()
        server_page.actions.selectServerOs(3)
        server_page.actions.clickConfirmOsBtn()
        cy.wait(5000)
        server_page.actions.clickServerTitleField()
        server_page.actions.writeTitle(serverName)
        server_page.actions.writeDesc("Test Description about Server")
        server_page.actions.writeCpuTxt(2)
        server_page.actions.writeRamTxt(4)
        server_page.actions.toggleBackupBtn()
        server_page.actions.isOpenedModal()
        server_page.actions.writeBackupTitle("Test_Backup")
        server_page.actions.clickBackupCopiesBtn()
        server_page.actions.writeBackupCopiesTxt('0')
        server_page.actions.checkConfirmBackupCopyBtn()
    })
    it('[PD-23] Создать новый сервер с неправильными ресурсами (SSD Disk больше лимита)', () => {
        const serverName = faker.lorem.word() + Math.round(Math.random() * 10000)

        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        server_page.actions.clickCreateServerBtn()
        server_page.actions.checkCreateServerPageLbl()
        server_page.actions.clickOsTxt()
        server_page.actions.isOpenedModal()
        server_page.actions.selectServerOs(3)
        server_page.actions.clickConfirmOsBtn()
        cy.wait(7000)
        server_page.actions.clickServerTitleField()
        server_page.actions.writeTitle(serverName)
        server_page.actions.writeDesc("Test Description about Server")
        server_page.actions.writeCpuTxt(2)
        server_page.actions.writeRamTxt(4)
        server_page.actions.clickDiskTypeSSDBtn()
        server_page.actions.typeDiskSize(500000)
        server_page.actions.enablePublicIp()
        server_page.actions.isRedDiskTxt1()
    })
    it('[PD-24] Создать новый сервер с неправильными ресурсами (SSD Disk негативное число)', () => {
        const serverName = faker.lorem.word() + Math.round(Math.random() * 10000)

        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        server_page.actions.clickCreateServerBtn()
        server_page.actions.checkCreateServerPageLbl()
        server_page.actions.clickOsTxt()
        server_page.actions.isOpenedModal()
        server_page.actions.selectServerOs(3)
        server_page.actions.clickConfirmOsBtn()
        cy.wait(2000)
        server_page.actions.clickServerTitleField()
        server_page.actions.writeTitle(serverName)
        server_page.actions.writeDesc("Test Description about Server")
        server_page.actions.writeCpuTxt(2)
        server_page.actions.writeRamTxt(4)
        server_page.actions.clickDiskTypeSSDBtn()
        server_page.actions.typeDiskSize(-50)
        server_page.actions.enablePublicIp()
        server_page.actions.isRedDiskTxt1()
    })
    it('[PD-30] Создать новый сервер с новой локальной сетью и некорректный формат поля IP (остальные поле корректные)', () => {
        const serverName = faker.lorem.word() + Math.round(Math.random() * 10000)
        const localIpName = faker.lorem.word()
        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        server_page.actions.clickCreateServerBtn()
        server_page.actions.checkCreateServerPageLbl()
        server_page.actions.clickOsTxt()
        server_page.actions.isOpenedModal()
        server_page.actions.selectServerOs(3)
        server_page.actions.clickConfirmOsBtn()
        cy.wait(5000)
        server_page.actions.clickServerTitleField()
        server_page.actions.writeTitle(serverName)
        server_page.actions.writeDesc("Test Description about Server")
        server_page.actions.writeCpuTxt(2)
        server_page.actions.writeRamTxt(4)
        server_page.actions.enableLocalIp(),
            server_page.actions.clickLocalIpSelector()
        server_page.actions.selectLocalIpName(configData.test_local_ip)
        server_page.actions.clickLocalIpAddNewBtn()
        server_page.actions.writeLocalIpNameTxt(`Test_IP_${localIpName}`)
        server_page.actions.writeLocalIpAddressTxt("1.1168.1.0")
        server_page.actions.writeLocalIpGatewayTxt("1.1168.1.1")
        server_page.actions.clickLocalIpAddConfBtn()
        server_page.actions.checkLocalIpErrorLbl("Неверное значение")
    })
    it('[PD-31] Создать новый сервер с новой локальной сетью и пустое поле Адрес подсети (остальные поле корректные)', () => {
        const serverName = faker.lorem.word() + Math.round(Math.random() * 10000)
        const localIpName = faker.lorem.word()
        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        server_page.actions.clickCreateServerBtn()
        server_page.actions.checkCreateServerPageLbl()
        server_page.actions.clickOsTxt()
        server_page.actions.isOpenedModal()
        server_page.actions.selectServerOs(3)
        server_page.actions.clickConfirmOsBtn()
        cy.wait(7000)
        server_page.actions.clickServerTitleField()
        server_page.actions.writeTitle(serverName)
        server_page.actions.writeDesc("Test Description about Server")
        server_page.actions.writeCpuTxt(2)
        server_page.actions.writeRamTxt(4)
        server_page.actions.enableLocalIp(),
            server_page.actions.clickLocalIpSelector()
        server_page.actions.selectLocalIpName(configData.test_local_ip)
        server_page.actions.clickLocalIpAddNewBtn()
        server_page.actions.writeLocalIpNameTxt(`Test_IP_${localIpName}`)
        server_page.actions.clickLocalIpAddConfBtn()
        server_page.actions.isRedLocalIpAddressTxt()
        server_page.actions.checkLocalIpErrorLbl("Обязательное поле")
    })
    it('[PD-114] Создать новый сервер с указанием локального IP и пустым названием новой сети', () => {
        const serverName = faker.lorem.word() + Math.round(Math.random() * 10000)
        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        server_page.actions.clickCreateServerBtn()
        server_page.actions.checkCreateServerPageLbl()
        server_page.actions.clickOsTxt()
        server_page.actions.isOpenedModal()
        server_page.actions.selectServerOs(3)
        server_page.actions.clickConfirmOsBtn()
        cy.wait(2000)
        server_page.actions.clickServerTitleField()
        server_page.actions.writeTitle(serverName)
        server_page.actions.writeDesc("Test Description about Server")
        server_page.actions.writeCpuTxt(2)
        server_page.actions.writeRamTxt(4)
        server_page.actions.enableLocalIp(),
            server_page.actions.clickLocalIpAddNewBtn()
        server_page.actions.clickLocalIpAddConfBtn()
        server_page.actions.isRedLocalIpTitleTxt()
        server_page.actions.checkLocalIpTitleErrorLbl("Обязательное поле")
    })
    it('[PD-106] Создать новый сервер, с локальным IP, выбрав уже имеющуюся локальную сеть из списка', () => {
        const serverName = faker.lorem.word() + Math.round(Math.random() * 10000)
        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        server_page.actions.clickCreateServerBtn()
        server_page.actions.checkCreateServerPageLbl()
        server_page.actions.clickOsTxt()
        server_page.actions.isOpenedModal()
        server_page.actions.selectServerOs(3)
        server_page.actions.clickConfirmOsBtn()
        cy.wait(4000)
        server_page.actions.clickServerTitleField()
        server_page.actions.writeTitle(serverName)
        server_page.actions.writeDesc("Test Description about Server")
        server_page.actions.writeCpuTxt(2)
        server_page.actions.writeRamTxt(4)
        server_page.actions.enableLocalIp()
        server_page.actions.clickLocalIpSelector()
        server_page.actions.selectLocalIpName(configData.test_local_ip)
        // server_page.actions.checkLocalIpAddressTxtNotEmpty()
        // server_page.actions.checkLocalIpTxtNotEmpty()
    })
})