cy.on('uncaught:exception', (err, runnable) => {
    return false;
});
const { faker } = require('@faker-js/faker');
import server_page from "../pages/server_page";
import sidebar from "../pages/sidebar";
import configuration_page from "../pages/configuration_page";
import serverlist_page from "../pages/server-list_page";
import serverAction_page from "../pages/server-action_page";

describe('3.Create Server Tests Part2', () => {
    let configData;
    before(() => {
        cy.fixture('examples').then((data) => {
            configData = data;
        });
    })
    beforeEach(() => {
        cy.viewport(1920, 1080)
        cy.intercept('POST', `${configData.base_url}panel-main/api/v1/auth/sign-in`).as('signInRequest');
        cy.intercept('POST', `${configData.base_url}panel-main/api/panel/vm/prepare`).as('createServerRequest');
        cy.intercept('POST', `${configData.base_url}panel-main/api/panel/vm/resourceMetaData`).as('resourcePrices');
    })
    it('[PD-111] Add new server with invalid resources (HDD Disk more than limit)', () => {
        const serverName = faker.lorem.word() + Math.round(Math.random() * 10000)

        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        server_page.actions.clickCreateServerBtn()
        server_page.actions.checkCreateServerPageLbl()
        server_page.actions.selectServerOs(0)
        server_page.actions.selectVersionOs()
        server_page.actions.writeTitle(serverName)
        server_page.actions.writeDesc("Test Description about Server")
        server_page.actions.setCpu(2)
        server_page.actions.setRam(4)
        server_page.actions.setDisk(500000)
        server_page.actions.isDiskIncreaseBtnDisabled()
    })
    it('[PD-112] Add new server with invalid resources (HDD Disk negative number)', () => {
        const serverName = faker.lorem.word() + Math.round(Math.random() * 10000)

        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        server_page.actions.clickCreateServerBtn()
        server_page.actions.checkCreateServerPageLbl()
        server_page.actions.selectServerOs(0)
        server_page.actions.selectVersionOs()
        server_page.actions.writeTitle(serverName)
        server_page.actions.writeDesc("Test Description about Server")
        server_page.actions.setCpu(2)
        server_page.actions.setRam(4)
        server_page.actions.setDisk(-50)
        server_page.actions.isDiskDescreaseBtnDisabled()
    })
    // it('[PD-26] Add new server with invalid backup name (cyrillic)', () => {      NOT ACTUAL ANYMORE (cyrilic can be entered now)
    //     const serverName = faker.lorem.word() + Math.round(Math.random() * 10000)

    //     cy.login(configData.base_url, configData.login, configData.password)
    //     sidebar.actions.clickServersIcon()
    //     server_page.actions.checkServerPageLbl()
    //     server_page.actions.clickCreateServerBtn()
    //     server_page.actions.checkCreateServerPageLbl()
    //     server_page.actions.selectServerOs(0)
    //     server_page.actions.writeTitle(serverName)
    //     server_page.actions.writeDesc("Test Description about Server")
    //     server_page.actions.setCpu(2)
    //     server_page.actions.setRam(4)
    //     server_page.actions.toggleBackupBtn()
    //     server_page.actions.writeBackupTitle("Тест Бэкап")
    //     server_page.actions.clickBackupCopiesBtn()
    //     server_page.actions.writeBackupCopiesTxt(2)
    //     server_page.actions.clickConfirmBackupCopyBtn()
    //     server_page.actions.selectBackupPeriod(2)
    //     server_page.actions.writeTimeSelector(0)
    //     server_page.actions.clickConfirmBackupBtn()
    // })
    it('[PD-27] Add new server with invalid backup schedule name (empty value)', () => {
        const serverName = faker.lorem.word() + Math.round(Math.random() * 10000)

        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        server_page.actions.clickCreateServerBtn()
        server_page.actions.checkCreateServerPageLbl()
        server_page.actions.selectServerOs(0)
        server_page.actions.selectVersionOs()
        server_page.actions.writeTitle(serverName)
        server_page.actions.writeDesc("Test Description about Server")
        server_page.actions.setCpu(2)
        server_page.actions.setRam(4)
        server_page.actions.toggleBackupBtn()
        server_page.actions.clickBackupCopiesBtn()
        server_page.actions.writeBackupCopiesTxt(2)
        server_page.actions.clickConfirmBackupCopyBtn()
        server_page.actions.selectBackupPeriod(2)
        server_page.actions.writeTimeSelector(0)
        server_page.actions.isBackupCopyBtnDisabled()
    })
    it('[PD-29] Add new server with invalid backup copies (zero)', () => {
        const serverName = faker.lorem.word() + Math.round(Math.random() * 10000)

        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        server_page.actions.clickCreateServerBtn()
        server_page.actions.checkCreateServerPageLbl()
        server_page.actions.selectServerOs(0)
        server_page.actions.selectVersionOs()
        server_page.actions.writeTitle(serverName)
        server_page.actions.writeDesc("Test Description about Server")
        server_page.actions.setCpu(2)
        server_page.actions.setRam(4)
        server_page.actions.toggleBackupBtn()
        server_page.actions.writeBackupTitle("Test_Backup")
        server_page.actions.clickBackupCopiesBtn()
        server_page.actions.writeBackupCopiesTxt('0')
    })
    it('[PD-23] Add new server with invalid resources (SSD Disk more than limit)', () => {
        const serverName = faker.lorem.word() + Math.round(Math.random() * 10000)

        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        server_page.actions.clickCreateServerBtn()
        server_page.actions.checkCreateServerPageLbl()
        server_page.actions.selectServerOs(0)
        server_page.actions.selectVersionOs()
        server_page.actions.writeTitle(serverName)
        server_page.actions.writeDesc("Test Description about Server")
        server_page.actions.setCpu(2)
        server_page.actions.setRam(4)
        server_page.actions.clickDiskTypeSSDBtn()
        server_page.actions.setDisk(500000)
        server_page.actions.isDiskIncreaseBtnDisabled()
    })
    it('[PD-24] Add new server with invalid resources (SSD Disk negative number)', () => {
        const serverName = faker.lorem.word() + Math.round(Math.random() * 10000)

        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        server_page.actions.clickCreateServerBtn()
        server_page.actions.checkCreateServerPageLbl()
        server_page.actions.selectServerOs(0)
        server_page.actions.selectVersionOs()
        server_page.actions.writeTitle(serverName)
        server_page.actions.writeDesc("Test Description about Server")
        server_page.actions.setCpu(2)
        server_page.actions.setRam(4)
        server_page.actions.clickDiskTypeSSDBtn()
        server_page.actions.setDisk(-50)
        server_page.actions.isDiskDescreaseBtnDisabled()
    })
    it('[PD-30] Add new server with invalid local network IP format (other fields correct)', () => {
        const serverName = faker.lorem.word() + Math.round(Math.random() * 10000)
        const localIpName = faker.lorem.word()
        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        server_page.actions.clickCreateServerBtn()
        server_page.actions.checkCreateServerPageLbl()
        server_page.actions.selectServerOs(0)
        server_page.actions.selectVersionOs()
        server_page.actions.writeTitle(serverName)
        server_page.actions.writeDesc("Test Description about Server")
        server_page.actions.setCpu(2)
        server_page.actions.setRam(4)
        server_page.actions.enableLocalIp()
        server_page.actions.clickLocalIpSelector()
        server_page.actions.selectLocalIpName(configData.test_local_ip)
        server_page.actions.clickLocalIpAddNewBtn()
         server_page.actions.writeLocalIpNameTxt(`Test_IP_${localIpName}`)
        server_page.actions.writeLocalIpAddressTxtforCustomOS("1.1168.1.0")
        server_page.actions.writeLocalIpGatewayTxt("1.1168.1.1")
        server_page.actions.clickLocalIpAddConfBtn()
        server_page.actions.checkLocalIpErrorLbl("Неверное значение")
    })
    it('[PD-31] Add new server with invalid local network subnet address (other fields correct)', () => {
        const serverName = faker.lorem.word() + Math.round(Math.random() * 10000)
        const localIpName = faker.lorem.word()
        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        server_page.actions.clickCreateServerBtn()
        server_page.actions.checkCreateServerPageLbl()
        server_page.actions.selectServerOs(0)
        server_page.actions.selectVersionOs()
        server_page.actions.writeTitle(serverName)
        server_page.actions.writeDesc("Test Description about Server")
        server_page.actions.setCpu(2)
        server_page.actions.setRam(4)
        server_page.actions.enableLocalIp()
        server_page.actions.clickLocalIpSelector()
        server_page.actions.selectLocalIpName(configData.test_local_ip)
        server_page.actions.clickLocalIpAddNewBtn()
        server_page.actions.writeLocalIpNameTxt(`Test_IP_${localIpName}`)
        server_page.actions.isLocalIpAddConfBtnDisabled()
    })
    it('[PD-114] Add new server with invalid local network name (empty value)', () => {
        const serverName = faker.lorem.word() + Math.round(Math.random() * 10000)
        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        server_page.actions.clickCreateServerBtn()
        server_page.actions.checkCreateServerPageLbl()
        server_page.actions.selectServerOs(0)
        server_page.actions.selectVersionOs()
        server_page.actions.writeTitle(serverName)
        server_page.actions.writeDesc("Test Description about Server")
        server_page.actions.setCpu(2)
        server_page.actions.setRam(4)
        server_page.actions.enableLocalIp()
        server_page.actions.clickLocalIpAddNewBtn()
        server_page.actions.isLocalIpAddConfBtnDisabled()
    })
    it('[PD-106] Add new server with existing local network IP, selecting from the list', () => {
        const serverName = faker.lorem.word() + Math.round(Math.random() * 10000)
        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        server_page.actions.clickCreateServerBtn()
        server_page.actions.checkCreateServerPageLbl()
        server_page.actions.selectServerOs(0)
        server_page.actions.selectVersionOs()
        server_page.actions.writeTitle(serverName)
        server_page.actions.writeDesc("Test Description about Server")
        server_page.actions.setCpu(2)
        server_page.actions.setRam(4)
        server_page.actions.enableLocalIp()
        server_page.actions.clickLocalIpSelector()
        server_page.actions.selectLocalIpName(configData.test_local_ip)
        server_page.actions.checkLocalIpAddressTxtNotEmpty()
        server_page.actions.checkLocalIpTxtNotEmpty()
    })
})
//Test-Server won't be touched here