cy.on('uncaught:exception', (err, runnable) => {
    return false;
});
const { faker } = require('@faker-js/faker');
import server_page from "../pages/server_page";
import sidebar from "../pages/sidebar";
import serverlist_page from "../pages/server-list_page";
import serverDisksPage from "../pages/server-disks-page";
import serverAction_page from "../pages/server-action_page";
import disks_page from "../pages/disks_page";

describe('7.Servers - Disks tab Part2', () => {
    let configData;
    function turnToNumb(str) { return parseFloat(str.replace(/\s/g, '')) }
    before(() => {
        cy.fixture('examples').then((data) => {
            configData = data;
        });
    })
    beforeEach(() => {
        cy.viewport(1280, 720)
        cy.intercept('POST', `${configData.base_url}panel-main/api/v1/auth/sign-in`).as('signInRequest');
        cy.intercept('POST', `${configData.base_url}panel-main/api/panel/vm/${configData.test_server_id}/disks/add?need_reboot=false`).as('createNewDisk');
        cy.intercept('POST', `${configData.base_url}panel-main/api/panel/vm/resourceMetaData`).as('resourcePrices');
        cy.intercept('POST', `${configData.base_url}panel-main/api/panel/disk/${configData.test_server_id}/linkDisk/${configData.test_disk_id}`).as('linkDisk');
    })
    it("[PD-665] Создать NVME диск", () => { // Test Cases 665-700
        const diskName = "Test-NVME-Disk"
        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        serverlist_page.actions.searchServer(configData.test_server_name)
        serverlist_page.actions.isVisibleSearchTxtServer(configData.test_server_name)
        serverlist_page.actions.clickServerCard(configData.test_server_name)
        serverlist_page.actions.isVisibleServerDetail(configData.test_server_name)
        serverDisksPage.actions.clickServerDisksTab()
        serverDisksPage.actions.clickAddNewServerDiskBtn()
        serverDisksPage.actions.writeNewDiskNameTxt(diskName)
        serverDisksPage.actions.clickDiskTypeNVMEBtn()
        serverDisksPage.actions.clickConfirmNewDiskBtn()
        //serverDisksPage.actions.checkCreateDiskAPI(diskName)
        serverDisksPage.actions.isVisibleCreatedDisk(diskName)
    })
    it("[PD-689] Создать NVME диск (пустое называние)", () => {
        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        serverlist_page.actions.searchServer(configData.test_server_name)
        serverlist_page.actions.isVisibleSearchTxtServer(configData.test_server_name)
        serverlist_page.actions.clickServerCard(configData.test_server_name)
        serverlist_page.actions.isVisibleServerDetail(configData.test_server_name)
        serverDisksPage.actions.clickServerDisksTab()
        serverDisksPage.actions.clickAddNewServerDiskBtn()
        serverDisksPage.actions.clickDiskTypeNVMEBtn()
        serverDisksPage.actions.clickConfirmNewDiskBtn()
        serverDisksPage.actions.checkNewDiskNameErrorLbl("Обязательное поле")
    })
    it("[PD-690] Создать NVME диск (математические символы)", () => {
        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        serverlist_page.actions.searchServer(configData.test_server_name)
        serverlist_page.actions.isVisibleSearchTxtServer(configData.test_server_name)
        serverlist_page.actions.clickServerCard(configData.test_server_name)
        serverlist_page.actions.isVisibleServerDetail(configData.test_server_name)
        serverDisksPage.actions.clickServerDisksTab()
        serverDisksPage.actions.clickAddNewServerDiskBtn()
        serverDisksPage.actions.clickDiskTypeNVMEBtn()
        serverDisksPage.actions.writeNewDiskNameTxt("+_-().,*&^%$£")
        serverDisksPage.actions.clickConfirmNewDiskBtn()
        serverDisksPage.actions.checkNewDiskNameContainsErrorLbl("Неверное название")
    })
    it("[PD-691] Создать NVME диск (менее 3 символов)", () => {
        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        serverlist_page.actions.searchServer(configData.test_server_name)
        serverlist_page.actions.isVisibleSearchTxtServer(configData.test_server_name)
        serverlist_page.actions.clickServerCard(configData.test_server_name)
        serverlist_page.actions.isVisibleServerDetail(configData.test_server_name)
        serverDisksPage.actions.clickServerDisksTab()
        serverDisksPage.actions.clickAddNewServerDiskBtn()
        serverDisksPage.actions.clickDiskTypeNVMEBtn()
        serverDisksPage.actions.writeNewDiskNameTxt("Ab")
        serverDisksPage.actions.clickConfirmNewDiskBtn()
        serverDisksPage.actions.checkNewDiskNameContainsErrorLbl("Минимум 3 символа")
    })
    it("[PD-692] Создать NVME диск (не латиница)", () => {
        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        serverlist_page.actions.searchServer(configData.test_server_name)
        serverlist_page.actions.isVisibleSearchTxtServer(configData.test_server_name)
        serverlist_page.actions.clickServerCard(configData.test_server_name)
        serverlist_page.actions.isVisibleServerDetail(configData.test_server_name)
        serverDisksPage.actions.clickServerDisksTab()
        serverDisksPage.actions.clickAddNewServerDiskBtn()
        serverDisksPage.actions.clickDiskTypeNVMEBtn()
        serverDisksPage.actions.writeNewDiskNameTxt("тест")
        serverDisksPage.actions.clickConfirmNewDiskBtn()
        serverDisksPage.actions.checkNewDiskNameContainsErrorLbl("Неверное название")
    })
    it("[PD-693] Создать NVME диск (только цифры)", () => {
        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        serverlist_page.actions.searchServer(configData.test_server_name)
        serverlist_page.actions.isVisibleSearchTxtServer(configData.test_server_name)
        serverlist_page.actions.clickServerCard(configData.test_server_name)
        serverlist_page.actions.isVisibleServerDetail(configData.test_server_name)
        serverDisksPage.actions.clickServerDisksTab()
        serverDisksPage.actions.clickAddNewServerDiskBtn()
        serverDisksPage.actions.clickDiskTypeNVMEBtn()
        serverDisksPage.actions.writeNewDiskNameTxt("123456")
        serverDisksPage.actions.clickConfirmNewDiskBtn()
        serverDisksPage.actions.checkNewDiskNameContainsErrorLbl("Неверное название")
    })
    it("[PD-694] Создать NVME диск — кнопка X", () => {
        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        serverlist_page.actions.searchServer(configData.test_server_name)
        serverlist_page.actions.isVisibleSearchTxtServer(configData.test_server_name)
        serverlist_page.actions.clickServerCard(configData.test_server_name)
        serverlist_page.actions.isVisibleServerDetail(configData.test_server_name)
        serverDisksPage.actions.clickServerDisksTab()
        serverDisksPage.actions.clickAddNewServerDiskBtn()
        serverDisksPage.actions.clickModalCloseBtn()
        serverDisksPage.actions.checkAddDiskBtnExists()
    })
    it("[PD-695] Изменить имя диска NVME - кнопка «Отмена»", () => {
        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        serverlist_page.actions.searchServer(configData.test_server_name)
        serverlist_page.actions.isVisibleSearchTxtServer(configData.test_server_name)
        serverlist_page.actions.clickServerCard(configData.test_server_name)
        serverlist_page.actions.isVisibleServerDetail(configData.test_server_name)
        serverDisksPage.actions.clickServerDisksTab()
        serverDisksPage.actions.clickRenameDiskBtn()
        serverDisksPage.actions.clickCancelBtnInRenameModal()
        serverDisksPage.actions.checkAddDiskBtnExists()
    })
    it("[PD-667] Изменить имя диска NVME (пустое называние)", () => {
        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        serverlist_page.actions.searchServer(configData.test_server_name)
        serverlist_page.actions.isVisibleSearchTxtServer(configData.test_server_name)
        serverlist_page.actions.clickServerCard(configData.test_server_name)
        serverlist_page.actions.isVisibleServerDetail(configData.test_server_name)
        serverDisksPage.actions.clickServerDisksTab()
        serverDisksPage.actions.clickRenameDiskBtn()
        serverDisksPage.actions.clearTextInRenameDiskNameModal()
        serverDisksPage.actions.clickConfirmBtnInRenameModal()
        serverDisksPage.actions.checkRenamedDiskNameErrorLbl("Обязательное поле")
    })
    it("[PD-668] Изменить имя диска NVME (неизмененное называние)", () => {
        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        serverlist_page.actions.searchServer(configData.test_server_name)
        serverlist_page.actions.isVisibleSearchTxtServer(configData.test_server_name)
        serverlist_page.actions.clickServerCard(configData.test_server_name)
        serverlist_page.actions.isVisibleServerDetail(configData.test_server_name)
        serverDisksPage.actions.clickServerDisksTab()
        serverDisksPage.actions.clickRenameDiskBtn()
        serverDisksPage.actions.isDisabledRenameDiskModalConfirmBtn()
    })
    it("[PD-669] Изменить имя диска NVME (математические символы)", () => {
        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        serverlist_page.actions.searchServer(configData.test_server_name)
        serverlist_page.actions.isVisibleSearchTxtServer(configData.test_server_name)
        serverlist_page.actions.clickServerCard(configData.test_server_name)
        serverlist_page.actions.isVisibleServerDetail(configData.test_server_name)
        serverDisksPage.actions.clickServerDisksTab()
        serverDisksPage.actions.clickRenameDiskBtn()
        serverDisksPage.actions.editDiskNameTxt("+_-().,*&^%$£")
        serverDisksPage.actions.clickConfirmBtnInRenameModal()
        serverDisksPage.actions.checkRenamedDiskNameContainsErrorLbl("Неверное название")
    })
    it("[PD-670] Изменить имя диска NVME (менее 3 символов)", () => {
        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        serverlist_page.actions.searchServer(configData.test_server_name)
        serverlist_page.actions.isVisibleSearchTxtServer(configData.test_server_name)
        serverlist_page.actions.clickServerCard(configData.test_server_name)
        serverlist_page.actions.isVisibleServerDetail(configData.test_server_name)
        serverDisksPage.actions.clickServerDisksTab()
        serverDisksPage.actions.clickRenameDiskBtn()
        serverDisksPage.actions.editDiskNameTxt("Ab")
        serverDisksPage.actions.clickConfirmBtnInRenameModal()
        serverDisksPage.actions.checkRenamedDiskNameContainsErrorLbl("Минимум 3 символа")
    })
    it("[PD-671] Изменить имя диска NVME (не латиница)", () => {
        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        serverlist_page.actions.searchServer(configData.test_server_name)
        serverlist_page.actions.isVisibleSearchTxtServer(configData.test_server_name)
        serverlist_page.actions.clickServerCard(configData.test_server_name)
        serverlist_page.actions.isVisibleServerDetail(configData.test_server_name)
        serverDisksPage.actions.clickServerDisksTab()
        serverDisksPage.actions.clickRenameDiskBtn()
        serverDisksPage.actions.editDiskNameTxt("тест")
        serverDisksPage.actions.clickConfirmBtnInRenameModal()
        serverDisksPage.actions.checkRenamedDiskNameContainsErrorLbl("Неверное название")
    })
    it("[PD-672] Изменить имя диска NVME (только цифры)", () => {
        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        serverlist_page.actions.searchServer(configData.test_server_name)
        serverlist_page.actions.isVisibleSearchTxtServer(configData.test_server_name)
        serverlist_page.actions.clickServerCard(configData.test_server_name)
        serverlist_page.actions.isVisibleServerDetail(configData.test_server_name)
        serverDisksPage.actions.clickServerDisksTab()
        serverDisksPage.actions.clickRenameDiskBtn()
        serverDisksPage.actions.editDiskNameTxt("123456")
        serverDisksPage.actions.clickConfirmBtnInRenameModal()
        serverDisksPage.actions.checkRenamedDiskNameContainsErrorLbl("Неверное название")
    })
    it("[PD-666] Изменить имя диска NVME", () => {
        const editedDiskName = "Test-Edited-NVME-Disk"
        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        serverlist_page.actions.searchServer(configData.test_server_name)
        serverlist_page.actions.isVisibleSearchTxtServer(configData.test_server_name)
        serverlist_page.actions.clickServerCard(configData.test_server_name)
        serverlist_page.actions.isVisibleServerDetail(configData.test_server_name)
        serverDisksPage.actions.clickServerDisksTab()
        serverDisksPage.actions.clickRenameDiskBtn()
        serverDisksPage.actions.editDiskNameTxt(editedDiskName)
        serverDisksPage.actions.clickConfirmBtnInRenameModal()
        serverDisksPage.actions.isVisibleCreatedDisk(editedDiskName)
    })
    it("[PD-678] Увеличить NVME диск вручную - Без перезагрузки сервера", () => {
        const number = 20;
        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        serverlist_page.actions.searchServer(configData.test_server_name)
        serverlist_page.actions.isVisibleSearchTxtServer(configData.test_server_name)
        serverlist_page.actions.clickServerCard(configData.test_server_name)
        serverlist_page.actions.isVisibleServerDetail(configData.test_server_name)
        serverDisksPage.actions.clickServerDisksTab()
        serverDisksPage.actions.clickNvmeIncreaseDiskSizeBtn()
        serverDisksPage.actions.clickWithoutServerRebootIncreaseDiskSizeBtn()
        serverDisksPage.actions.writeDiskSizeUpModalTxt(number)
        serverDisksPage.actions.clickDiskSizeUpModalBtn()
        serverDisksPage.actions.isVisibleCreatedDisk(number)
    })
    it("[PD-680] Увеличить NVME диск вручную - Без перезагрузки сервера (математические символы)", () => {
        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        serverlist_page.actions.searchServer(configData.test_server_name)
        serverlist_page.actions.isVisibleSearchTxtServer(configData.test_server_name)
        serverlist_page.actions.clickServerCard(configData.test_server_name)
        serverlist_page.actions.isVisibleServerDetail(configData.test_server_name)
        serverDisksPage.actions.clickServerDisksTab()
        serverDisksPage.actions.clickNvmeIncreaseDiskSizeBtn()
        serverDisksPage.actions.clickWithoutServerRebootIncreaseDiskSizeBtn()
        serverDisksPage.actions.writeDiskSizeUpModalTxt('+')
        serverDisksPage.actions.isDisabledDiskSizeUpModalBtn()
    })
    it("[PD-681] Увеличить NVME диск вручную - Без перезагрузки сервера (больше максимального лимита)", () => {
        const number = 10000;
        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        serverlist_page.actions.searchServer(configData.test_server_name)
        serverlist_page.actions.isVisibleSearchTxtServer(configData.test_server_name)
        serverlist_page.actions.clickServerCard(configData.test_server_name)
        serverlist_page.actions.isVisibleServerDetail(configData.test_server_name)
        serverDisksPage.actions.clickServerDisksTab()
        serverDisksPage.actions.clickNvmeIncreaseDiskSizeBtn()
        serverDisksPage.actions.clickWithoutServerRebootIncreaseDiskSizeBtn()
        serverDisksPage.actions.writeDiskSizeUpModalTxt(number)
        serverDisksPage.actions.clickDiskSizeUpModalBtn()
        serverDisksPage.actions.checkNewDiskSizeErrorLbl2("Максимальный размер диска 1000 Гб. Для расширения ограничения обратитесь в техническую поддержку Pro-Data")
    })
    it("[PD-682] Увеличить NVME диск вручную - Без перезагрузки сервера (0)", () => {
        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        serverlist_page.actions.searchServer(configData.test_server_name)
        serverlist_page.actions.isVisibleSearchTxtServer(configData.test_server_name)
        serverlist_page.actions.clickServerCard(configData.test_server_name)
        serverlist_page.actions.isVisibleServerDetail(configData.test_server_name)
        serverDisksPage.actions.clickServerDisksTab()
        serverDisksPage.actions.clickNvmeIncreaseDiskSizeBtn()
        serverDisksPage.actions.clickWithoutServerRebootIncreaseDiskSizeBtn()
        serverDisksPage.actions.writeDiskSizeUpModalTxt('0')
        serverDisksPage.actions.clickDiskSizeUpModalBtn()
        serverDisksPage.actions.checkNewDiskSizeErrorLbl2('Неверное значение')
    })
    it("[PD-673] Увеличить NVME диск автоматически - С перезагрузкой серверa", () => {
        const number = 30;
        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        serverlist_page.actions.searchServer(configData.test_server_name)
        serverlist_page.actions.isVisibleSearchTxtServer(configData.test_server_name)
        serverlist_page.actions.clickServerCard(configData.test_server_name)
        serverlist_page.actions.isVisibleServerDetail(configData.test_server_name)
        serverDisksPage.actions.clickServerDisksTab()
        serverDisksPage.actions.clickNvmeIncreaseDiskSizeBtn()
        serverDisksPage.actions.clickWithServerRebootIncreaseDiskSizeBtn()
        serverDisksPage.actions.writeDiskSizeUpModalTxt(number)
        serverDisksPage.actions.clickDiskSizeUpModalBtn()
        cy.wait(50000)
        serverAction_page.actions.clickServerActionsBtn()
        cy.wait(2000)
        serverAction_page.actions.clickStopServerBtn()
        cy.wait(2000)
        try {
            serverAction_page.actions.isServerStoppedStatus()
        } catch {
            cy.wait(30000)
            serverAction_page.actions.isServerStoppedStatus()
        }
        serverDisksPage.actions.isVisibleCreatedDisk(number)
    })
    it("[PD-675] Увеличить NVME диск автоматически - С перезагрузкой серверa (математические символы)", () => {
        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        serverlist_page.actions.searchServer(configData.test_server_name)
        serverlist_page.actions.isVisibleSearchTxtServer(configData.test_server_name)
        serverlist_page.actions.clickServerCard(configData.test_server_name)
        serverlist_page.actions.isVisibleServerDetail(configData.test_server_name)
        serverDisksPage.actions.clickServerDisksTab()
        serverDisksPage.actions.clickNvmeIncreaseDiskSizeBtn()
        serverDisksPage.actions.clickWithServerRebootIncreaseDiskSizeBtn()
        serverDisksPage.actions.writeDiskSizeUpModalTxt('+')
        serverDisksPage.actions.isDisabledDiskSizeUpModalBtn()
    })
    it("[PD-676] Увеличить NVME диск автоматически - С перезагрузкой серверa (больше максимального лимита)", () => {
        const number = 10000;
        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        serverlist_page.actions.searchServer(configData.test_server_name)
        serverlist_page.actions.isVisibleSearchTxtServer(configData.test_server_name)
        serverlist_page.actions.clickServerCard(configData.test_server_name)
        serverlist_page.actions.isVisibleServerDetail(configData.test_server_name)
        serverDisksPage.actions.clickServerDisksTab()
        serverDisksPage.actions.clickNvmeIncreaseDiskSizeBtn()
        serverDisksPage.actions.clickWithServerRebootIncreaseDiskSizeBtn()
        serverDisksPage.actions.writeDiskSizeUpModalTxt(number)
        serverDisksPage.actions.clickDiskSizeUpModalBtn()
        serverDisksPage.actions.checkNewDiskSizeErrorLbl2("Максимальный размер диска 1000 Гб. Для расширения ограничения обратитесь в техническую поддержку Pro-Data")
    })
    it("[PD-677] Увеличить NVME диск автоматически - С перезагрузкой серверa (0)", () => {
        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        serverlist_page.actions.searchServer(configData.test_server_name)
        serverlist_page.actions.isVisibleSearchTxtServer(configData.test_server_name)
        serverlist_page.actions.clickServerCard(configData.test_server_name)
        serverlist_page.actions.isVisibleServerDetail(configData.test_server_name)
        serverDisksPage.actions.clickServerDisksTab()
        serverDisksPage.actions.clickNvmeIncreaseDiskSizeBtn()
        serverDisksPage.actions.clickWithServerRebootIncreaseDiskSizeBtn()
        serverDisksPage.actions.writeDiskSizeUpModalTxt('0')
        serverDisksPage.actions.clickDiskSizeUpModalBtn()
        serverDisksPage.actions.checkNewDiskSizeErrorLbl2('Неверное значение')
    })
    it("[PD-696] Увеличение размерa NVME дискa — кнопка X", () => {
        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        serverlist_page.actions.searchServer(configData.test_server_name)
        serverlist_page.actions.isVisibleSearchTxtServer(configData.test_server_name)
        serverlist_page.actions.clickServerCard(configData.test_server_name)
        serverlist_page.actions.isVisibleServerDetail(configData.test_server_name)
        serverDisksPage.actions.clickServerDisksTab()
        serverDisksPage.actions.clickNvmeIncreaseDiskSizeBtn()
        serverDisksPage.actions.clickModalCloseBtn()
        serverDisksPage.actions.checkAddDiskBtnExists()
    })
    it("[PD-683] Пометить NVME диск как загрузочным", () => {
        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        serverlist_page.actions.searchServer(configData.test_server_name)
        serverlist_page.actions.isVisibleSearchTxtServer(configData.test_server_name)
        serverlist_page.actions.clickServerCard(configData.test_server_name)
        serverlist_page.actions.isVisibleServerDetail(configData.test_server_name)
        serverDisksPage.actions.clickServerDisksTab()
        serverDisksPage.actions.clickNvmeDiskChangeToBootDiskBtn()
        serverDisksPage.actions.clickDiskmakeUploadConfirmBtn()
        cy.wait(2000)
        serverDisksPage.actions.checkNvmeDiskChangedToBootDisk()
    })
    it("[PD-686] Изменить NVME диск с загрузочного диска", () => {
        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        serverlist_page.actions.searchServer(configData.test_server_name)
        serverlist_page.actions.isVisibleSearchTxtServer(configData.test_server_name)
        serverlist_page.actions.clickServerCard(configData.test_server_name)
        serverlist_page.actions.isVisibleServerDetail(configData.test_server_name)
        serverDisksPage.actions.clickServerDisksTab()
        serverDisksPage.actions.clickBootDiskChangeToBootDiskBtn()
        serverDisksPage.actions.clickDiskmakeUploadConfirmBtn()
        cy.wait(2000)
        serverDisksPage.actions.checkBootDiskChangedToBootDisk()
    })
    it("[PD-697] Пометить NVME диск как загрузочный -  кнопка «Отмена»", () => {
        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        serverlist_page.actions.searchServer(configData.test_server_name)
        serverlist_page.actions.isVisibleSearchTxtServer(configData.test_server_name)
        serverlist_page.actions.clickServerCard(configData.test_server_name)
        serverlist_page.actions.isVisibleServerDetail(configData.test_server_name)
        serverDisksPage.actions.clickServerDisksTab()
        serverDisksPage.actions.clickNvmeDiskChangeToBootDiskBtn()
        serverDisksPage.actions.clickChangeToBootDiskModalCancelBtn()
        cy.wait(1000)
        serverDisksPage.actions.checkAddDiskBtnExists()
    })
    it("[PD-698] Отвязать NVME диск от ВМ - кнопка «Отмена»", () => {
        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        serverlist_page.actions.searchServer(configData.test_server_name)
        serverlist_page.actions.isVisibleSearchTxtServer(configData.test_server_name)
        serverlist_page.actions.clickServerCard(configData.test_server_name)
        serverlist_page.actions.isVisibleServerDetail(configData.test_server_name)
        serverDisksPage.actions.clickServerDisksTab()
        serverDisksPage.actions.clickNvmeDiskDetachBtn()
        serverDisksPage.actions.clickNvmeDiskDetachModalCancelBtn()
        cy.wait(1000)
        serverDisksPage.actions.checkAddDiskBtnExists()
    })
    it("[PD-685] Отвязать NVME диск от ВМ", () => {
        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        serverlist_page.actions.searchServer(configData.test_server_name)
        serverlist_page.actions.isVisibleSearchTxtServer(configData.test_server_name)
        serverlist_page.actions.clickServerCard(configData.test_server_name)
        serverlist_page.actions.isVisibleServerDetail(configData.test_server_name)
        serverDisksPage.actions.clickServerDisksTab()
        serverDisksPage.actions.clickNvmeDiskDetachBtn()
        serverDisksPage.actions.clickDisconnectDiskModalBtn()
        cy.wait(3000)
        serverDisksPage.actions.checkNvmeDiskNotExists()
        sidebar.actions.clickDisksIcon()
        serverDisksPage.actions.checkNvmeDiskExists()
    })
    it("[PD-701] Привязать NVME диск к BM - кнопка X", () => {
        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        serverlist_page.actions.searchServer(configData.test_server_name)
        serverlist_page.actions.isVisibleSearchTxtServer(configData.test_server_name)
        serverlist_page.actions.clickServerCard(configData.test_server_name)
        serverlist_page.actions.isVisibleServerDetail(configData.test_server_name)
        serverDisksPage.actions.clickServerDisksTab()
        serverDisksPage.actions.clickConnectNewServerDiskBtn()
        serverDisksPage.actions.clickModalCloseBtn()
        cy.wait(1000)
        serverDisksPage.actions.checkAddDiskBtnExists()
    })
    it("[PD-687] Привязать NVME диск к BM", () => {
        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        serverlist_page.actions.searchServer(configData.test_server_name)
        serverlist_page.actions.isVisibleSearchTxtServer(configData.test_server_name)
        serverlist_page.actions.clickServerCard(configData.test_server_name)
        serverlist_page.actions.isVisibleServerDetail(configData.test_server_name)
        serverDisksPage.actions.clickServerDisksTab()
        serverDisksPage.actions.clickConnectNewServerDiskBtn()
        serverDisksPage.actions.clickConnectDiskSelector()
        serverDisksPage.actions.selectConnectNvmeDiskOption()
        serverDisksPage.actions.clickConnectDiskModalBtn()
        cy.wait(1000)
        serverDisksPage.actions.checkNvmeDiskExists()
    })
    it("[PD-700] Удалить NVME диск из BM - кнопка «Отмена»", () => {
        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        serverlist_page.actions.searchServer(configData.test_server_name)
        serverlist_page.actions.isVisibleSearchTxtServer(configData.test_server_name)
        serverlist_page.actions.clickServerCard(configData.test_server_name)
        serverlist_page.actions.isVisibleServerDetail(configData.test_server_name)
        serverDisksPage.actions.clickServerDisksTab()
        serverDisksPage.actions.clickNvmeDiskDeleteBtn()
        serverDisksPage.actions.clickNvmeDiskDeleteModalCancelBtn()
        cy.wait(1000)
        serverDisksPage.actions.checkAddDiskBtnExists()
    })
    it("[PD-688] Удалить NVME диск из BM", () => {
        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        serverlist_page.actions.searchServer(configData.test_server_name)
        serverlist_page.actions.isVisibleSearchTxtServer(configData.test_server_name)
        serverlist_page.actions.clickServerCard(configData.test_server_name)
        serverlist_page.actions.isVisibleServerDetail(configData.test_server_name)
        serverDisksPage.actions.clickServerDisksTab()
        serverDisksPage.actions.clickNvmeDiskDeleteBtn()
        serverDisksPage.actions.clickConfDeleteBtn()
        cy.wait(1000)
        serverDisksPage.actions.checkNvmeDiskNotExists()
    })
})