cy.on('uncaught:exception', (err, runnable) => {
    return false;
});
const { faker } = require('@faker-js/faker');
import server_page from "../pages/server_page";
import sidebar from "../pages/sidebar";
import serverlist_page from "../pages/server-list_page";
import serverDisksPage from "../pages/server-disks-page";
import serverAction_page from "../pages/server-action_page";
import disks_page from "../pages/disks_page";

describe('7.Servers - Disks tab Part2', () => {
    let configData;
    function turnToNumb(str) { return parseFloat(str.replace(/\s/g, '')) }
    before(() => {
        cy.fixture('examples').then((data) => {
            configData = data;
        });
    })
    beforeEach(() => {
        cy.viewport(1280, 720)
        cy.intercept('POST', `${configData.base_url}panel-main/api/v1/auth/sign-in`).as('signInRequest');
        cy.intercept('POST', `${configData.base_url}panel-main/api/panel/vm/${configData.test_server_id}/disks/add?need_reboot=false`).as('createNewDisk');
        cy.intercept('POST', `${configData.base_url}panel-main/api/panel/vm/resourceMetaData`).as('resourcePrices');
        cy.intercept('POST', `${configData.base_url}panel-main/api/panel/disk/${configData.test_server_id}/linkDisk/${configData.test_disk_id}`).as('linkDisk');
    })
    it("[PD-665] Add NVME disk", () => { // Test Cases 665-700
        const diskName = "Test-NVME-Disk"
        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        serverlist_page.actions.searchServer(configData.test_server_name)
        serverlist_page.actions.isVisibleSearchTxtServer(configData.test_server_name)
        serverlist_page.actions.clickServerCard(configData.test_server_name)
        serverlist_page.actions.isVisibleServerDetail(configData.test_server_name)
        serverDisksPage.actions.clickServerDisksTab()
        serverDisksPage.actions.clickAddNewServerDiskBtn()
        serverDisksPage.actions.writeNewDiskNameTxt(diskName)
        serverDisksPage.actions.clickDiskTypeNVMEBtn()
        serverDisksPage.actions.clickConfirmNewDiskBtn()
        serverDisksPage.actions.isVisibleCreatedDisk(diskName)
    })
    it("[PD-689] Add NVME disk (empty name)", () => {
        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        serverlist_page.actions.searchServer(configData.test_server_name)
        serverlist_page.actions.isVisibleSearchTxtServer(configData.test_server_name)
        serverlist_page.actions.clickServerCard(configData.test_server_name)
        serverlist_page.actions.isVisibleServerDetail(configData.test_server_name)
        serverDisksPage.actions.clickServerDisksTab()
        serverDisksPage.actions.clickAddNewServerDiskBtn()
        serverDisksPage.actions.clickDiskTypeNVMEBtn()
        serverDisksPage.actions.clickConfirmNewDiskBtn()
        serverDisksPage.actions.checkNewDiskNameErrorLbl("Обязательное поле")
    })
    // it("[PD-690] Add NVME disk (math symbols)", () => {               // This test is not actual as of now field was changed by toggles - no way inserting chars
    //     cy.login(configData.base_url, configData.login, configData.password)
    //     sidebar.actions.clickServersIcon()
    //     server_page.actions.checkServerPageLbl()
    //     serverlist_page.actions.searchServer(configData.test_server_name)
    //     serverlist_page.actions.isVisibleSearchTxtServer(configData.test_server_name)
    //     serverlist_page.actions.clickServerCard(configData.test_server_name)
    //     serverlist_page.actions.isVisibleServerDetail(configData.test_server_name)
    //     serverDisksPage.actions.clickServerDisksTab()
    //     serverDisksPage.actions.clickAddNewServerDiskBtn()
    //     serverDisksPage.actions.clickDiskTypeNVMEBtn()
    //     serverDisksPage.actions.writeNewDiskNameTxt("+_-().,*&^%$£")
    //     serverDisksPage.actions.clickConfirmNewDiskBtn()
    //     serverDisksPage.actions.checkNewDiskNameContainsErrorLbl("Неверное название")
    // })
    it("[PD-691] Add NVME disk (less than 3 chars)", () => {
        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        serverlist_page.actions.searchServer(configData.test_server_name)
        serverlist_page.actions.isVisibleSearchTxtServer(configData.test_server_name)
        serverlist_page.actions.clickServerCard(configData.test_server_name)
        serverlist_page.actions.isVisibleServerDetail(configData.test_server_name)
        serverDisksPage.actions.clickServerDisksTab()
        serverDisksPage.actions.clickAddNewServerDiskBtn()
        serverDisksPage.actions.clickDiskTypeNVMEBtn()
        serverDisksPage.actions.writeNewDiskNameTxt("Ab")
        serverDisksPage.actions.clickConfirmNewDiskBtn()
        serverDisksPage.actions.checkNewDiskNameContainsErrorLbl("Минимум 3 символа")
    })
    it("[PD-692] Add NVME disk (not Latin)", () => {
        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        serverlist_page.actions.searchServer(configData.test_server_name)
        serverlist_page.actions.isVisibleSearchTxtServer(configData.test_server_name)
        serverlist_page.actions.clickServerCard(configData.test_server_name)
        serverlist_page.actions.isVisibleServerDetail(configData.test_server_name)
        serverDisksPage.actions.clickServerDisksTab()
        serverDisksPage.actions.clickAddNewServerDiskBtn()
        serverDisksPage.actions.clickDiskTypeNVMEBtn()
        serverDisksPage.actions.writeNewDiskNameTxt("тест")
        serverDisksPage.actions.clickConfirmNewDiskBtn()
        serverDisksPage.actions.checkNewDiskNameContainsErrorLbl("Неверное название")
    })
    it("[PD-693] Add NVME disk (numbers only)", () => {
        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        serverlist_page.actions.searchServer(configData.test_server_name)
        serverlist_page.actions.isVisibleSearchTxtServer(configData.test_server_name)
        serverlist_page.actions.clickServerCard(configData.test_server_name)
        serverlist_page.actions.isVisibleServerDetail(configData.test_server_name)
        serverDisksPage.actions.clickServerDisksTab()
        serverDisksPage.actions.clickAddNewServerDiskBtn()
        serverDisksPage.actions.clickDiskTypeNVMEBtn()
        serverDisksPage.actions.writeNewDiskNameTxt("123456")
        serverDisksPage.actions.clickConfirmNewDiskBtn()
        serverDisksPage.actions.checkNewDiskNameContainsErrorLbl("Неверное название")
    })
    it("[PD-694] Add NVME disk — close button", () => {
        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        serverlist_page.actions.searchServer(configData.test_server_name)
        serverlist_page.actions.isVisibleSearchTxtServer(configData.test_server_name)
        serverlist_page.actions.clickServerCard(configData.test_server_name)
        serverlist_page.actions.isVisibleServerDetail(configData.test_server_name)
        serverDisksPage.actions.clickServerDisksTab()
        serverDisksPage.actions.clickAddNewServerDiskBtn()
        serverDisksPage.actions.clickModalCloseBtn()
        serverDisksPage.actions.checkAddDiskBtnExists()
    })
    it("[PD-695] Rename NVME disk - «Cancel» button", () => {
        const diskName = "Test-NVME-Disk"
        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        serverlist_page.actions.searchServer(configData.test_server_name)
        serverlist_page.actions.isVisibleSearchTxtServer(configData.test_server_name)
        serverlist_page.actions.clickServerCard(configData.test_server_name)
        serverlist_page.actions.isVisibleServerDetail(configData.test_server_name)
        serverDisksPage.actions.clickServerDisksTab()
        serverDisksPage.actions.clickRenameDiskBtn(diskName)
        serverDisksPage.actions.clickCancelBtnInRenameModal()
        serverDisksPage.actions.checkAddDiskBtnExists()
    })
    it("[PD-667] Rename NVME disk (empty name)", () => {
        const diskName = "Test-NVME-Disk"
        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        serverlist_page.actions.searchServer(configData.test_server_name)
        serverlist_page.actions.isVisibleSearchTxtServer(configData.test_server_name)
        serverlist_page.actions.clickServerCard(configData.test_server_name)
        serverlist_page.actions.isVisibleServerDetail(configData.test_server_name)
        serverDisksPage.actions.clickServerDisksTab()
        serverDisksPage.actions.clickRenameDiskBtn(diskName)
        serverDisksPage.actions.clearTextInRenameDiskNameModal()
        serverDisksPage.actions.IsDiskSubmitChangesBtnIsDisabled()
        serverDisksPage.actions.clickNvmeDiskSizeIncreaseBtn()  // just to wait for the error lbl to appear as of now there is no way to check it without this step
        serverDisksPage.actions.checkRenamedDiskNameErrorLbl("Обязательное поле")
    })
    it("[PD-668] Rename NVME disk (unchanged name)", () => {
        const diskName = "Test-NVME-Disk"
        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        serverlist_page.actions.searchServer(configData.test_server_name)
        serverlist_page.actions.isVisibleSearchTxtServer(configData.test_server_name)
        serverlist_page.actions.clickServerCard(configData.test_server_name)
        serverlist_page.actions.isVisibleServerDetail(configData.test_server_name)
        serverDisksPage.actions.clickServerDisksTab()
        serverDisksPage.actions.clickRenameDiskBtn(diskName)
        serverDisksPage.actions.IsDiskSubmitChangesBtnIsDisabled()
    })
    it("[PD-669] Rename NVME disk (math symbols)", () => {
        const diskName = "Test-NVME-Disk"
        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        serverlist_page.actions.searchServer(configData.test_server_name)
        serverlist_page.actions.isVisibleSearchTxtServer(configData.test_server_name)
        serverlist_page.actions.clickServerCard(configData.test_server_name)
        serverlist_page.actions.isVisibleServerDetail(configData.test_server_name)
        serverDisksPage.actions.clickServerDisksTab()
        serverDisksPage.actions.clickRenameDiskBtn(diskName)
        serverDisksPage.actions.editDiskNameTxt("+_-().,*&^%$£")
        serverDisksPage.actions.IsDiskSubmitChangesBtnIsDisabled()
        serverDisksPage.actions.clickNvmeDiskSizeIncreaseBtn()  // just to wait for the error lbl to appear as of now there is no way to check it without this step
        serverDisksPage.actions.checkRenamedDiskNameContainsErrorLbl("Неверное название")
    })
    it("[PD-670] Rename NVME disk (less than 3 chars)", () => {
        const diskName = "Test-NVME-Disk"
        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        serverlist_page.actions.searchServer(configData.test_server_name)
        serverlist_page.actions.isVisibleSearchTxtServer(configData.test_server_name)
        serverlist_page.actions.clickServerCard(configData.test_server_name)
        serverlist_page.actions.isVisibleServerDetail(configData.test_server_name)
        serverDisksPage.actions.clickServerDisksTab()
        serverDisksPage.actions.clickRenameDiskBtn(diskName)
        serverDisksPage.actions.editDiskNameTxt("Ab")
        serverDisksPage.actions.IsDiskSubmitChangesBtnIsDisabled()
        serverDisksPage.actions.clickNvmeDiskSizeIncreaseBtn()  // just to wait for the error lbl to appear as of now there is no way to check it without this step
        serverDisksPage.actions.checkRenamedDiskNameContainsErrorLbl("Минимум 3 символа")
    })
    it("[PD-671] Rename NVME disk (not Latin)", () => {
        const diskName = "Test-NVME-Disk"
        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        serverlist_page.actions.searchServer(configData.test_server_name)
        serverlist_page.actions.isVisibleSearchTxtServer(configData.test_server_name)
        serverlist_page.actions.clickServerCard(configData.test_server_name)
        serverlist_page.actions.isVisibleServerDetail(configData.test_server_name)
        serverDisksPage.actions.clickServerDisksTab()
        serverDisksPage.actions.clickRenameDiskBtn(diskName)
        serverDisksPage.actions.editDiskNameTxt("тест")
        serverDisksPage.actions.IsDiskSubmitChangesBtnIsDisabled()
        serverDisksPage.actions.clickNvmeDiskSizeIncreaseBtn()  // just to wait for the error lbl to appear as of now there is no way to check it without this step
        serverDisksPage.actions.checkRenamedDiskNameContainsErrorLbl("Неверное название")
    })
    it("[PD-672] Rename NVME disk (numbers only)", () => {
        const diskName = "Test-NVME-Disk"
        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        serverlist_page.actions.searchServer(configData.test_server_name)
        serverlist_page.actions.isVisibleSearchTxtServer(configData.test_server_name)
        serverlist_page.actions.clickServerCard(configData.test_server_name)
        serverlist_page.actions.isVisibleServerDetail(configData.test_server_name)
        serverDisksPage.actions.clickServerDisksTab()
        serverDisksPage.actions.clickRenameDiskBtn(diskName)
        serverDisksPage.actions.editDiskNameTxt("123456")
        serverDisksPage.actions.IsDiskSubmitChangesBtnIsDisabled()
        serverDisksPage.actions.clickNvmeDiskSizeIncreaseBtn()  // just to wait for the error lbl to appear as of now there is no way to check it without this step
        serverDisksPage.actions.checkRenamedDiskNameContainsErrorLbl("Неверное название")
    })
    it("[PD-666] Rename NVME disk (successfully)", () => {
        const diskName = "Test-NVME-Disk"
        const editedDiskName = "Test-Edited-NVME-Disk"
        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        serverlist_page.actions.searchServer(configData.test_server_name)
        serverlist_page.actions.isVisibleSearchTxtServer(configData.test_server_name)
        serverlist_page.actions.clickServerCard(configData.test_server_name)
        serverlist_page.actions.isVisibleServerDetail(configData.test_server_name)
        serverDisksPage.actions.clickServerDisksTab()
        serverDisksPage.actions.clickRenameDiskBtn(diskName)
        serverDisksPage.actions.editDiskNameTxt(editedDiskName)
        serverDisksPage.actions.clickDiskSaveBtnInChangesModal()
        serverDisksPage.actions.isVisibleCreatedDisk(editedDiskName)
    })
    it.only("[PD-678] Increase NVME disk manually - Without server reboot", () => {
        const editedDiskName = "Test-Edited-NVME-Disk"
        const number = 20;
        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        serverlist_page.actions.searchServer(configData.test_server_name)
        serverlist_page.actions.isVisibleSearchTxtServer(configData.test_server_name)
        serverlist_page.actions.clickServerCard(configData.test_server_name)
        serverlist_page.actions.isVisibleServerDetail(configData.test_server_name)
        serverDisksPage.actions.clickServerDisksTab()
        serverDisksPage.actions.clickRenameDiskBtn(editedDiskName)
        serverDisksPage.actions.clickWithoutServerRebootIncreaseDiskSizeBtn()
        serverDisksPage.actions.clickDiskSaveBtnInChangesModal()
        serverDisksPage.actions.isVisibleCreatedDisk(number)
    })
    // it("[PD-680] Increase NVME disk manually - without server reboot (math symbols)", () => {   This test is not actual as of now field was changed by toggles - no way inserting chars
    //     cy.login(configData.base_url, configData.login, configData.password)
    //     sidebar.actions.clickServersIcon()
    //     server_page.actions.checkServerPageLbl()
    //     serverlist_page.actions.searchServer(configData.test_server_name)
    //     serverlist_page.actions.isVisibleSearchTxtServer(configData.test_server_name)
    //     serverlist_page.actions.clickServerCard(configData.test_server_name)
    //     serverlist_page.actions.isVisibleServerDetail(configData.test_server_name)
    //     serverDisksPage.actions.clickServerDisksTab()
    //     serverDisksPage.actions.clickNvmeIncreaseDiskSizeBtn()
    //     serverDisksPage.actions.clickWithoutServerRebootIncreaseDiskSizeBtn()
    //     serverDisksPage.actions.writeDiskSizeUpModalTxt('+')
    //     serverDisksPage.actions.isDisabledDiskSizeUpModalBtn()
    // })
    it.only("[PD-681] Increase NVME disk manually - Without server reboot (more than max limit)", () => {
        const number = 10000;
        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        serverlist_page.actions.searchServer(configData.test_server_name)
        serverlist_page.actions.isVisibleSearchTxtServer(configData.test_server_name)
        serverlist_page.actions.clickServerCard(configData.test_server_name)
        serverlist_page.actions.isVisibleServerDetail(configData.test_server_name)
        serverDisksPage.actions.clickServerDisksTab()
        serverDisksPage.actions.clickNvmeIncreaseDiskSizeBtn()
        serverDisksPage.actions.clickWithoutServerRebootIncreaseDiskSizeBtn()
        serverDisksPage.actions.setDiskSize(number)
        serverDisksPage.actions.clickDiskSaveBtnInChangesModal()
        serverDisksPage.actions.checkNewDiskSizeErrorLbl2("Максимальный размер диска 1000 Гб. Для расширения ограничения обратитесь в техническую поддержку Pro-Data")
    })
    it.only("[PD-682] Increase NVME disk manually - Without server reboot (0)", () => {
        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        serverlist_page.actions.searchServer(configData.test_server_name)
        serverlist_page.actions.isVisibleSearchTxtServer(configData.test_server_name)
        serverlist_page.actions.clickServerCard(configData.test_server_name)
        serverlist_page.actions.isVisibleServerDetail(configData.test_server_name)
        serverDisksPage.actions.clickServerDisksTab()
        serverDisksPage.actions.clickNvmeIncreaseDiskSizeBtn()
        serverDisksPage.actions.clickWithoutServerRebootIncreaseDiskSizeBtn()
        serverDisksPage.actions.writeDiskSizeUpModalTxt('0')
        serverDisksPage.actions.clickDiskSizeUpModalBtn()
        serverDisksPage.actions.checkNewDiskSizeErrorLbl2('Неверное значение')
    })
    it("[PD-673] Increase NVME disk automatically - With server reboot", () => {
        const number = 30;
        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        serverlist_page.actions.searchServer(configData.test_server_name)
        serverlist_page.actions.isVisibleSearchTxtServer(configData.test_server_name)
        serverlist_page.actions.clickServerCard(configData.test_server_name)
        serverlist_page.actions.isVisibleServerDetail(configData.test_server_name)
        serverDisksPage.actions.clickServerDisksTab()
        serverDisksPage.actions.clickNvmeIncreaseDiskSizeBtn()
        serverDisksPage.actions.clickWithServerRebootIncreaseDiskSizeBtn()
        serverDisksPage.actions.writeDiskSizeUpModalTxt(number)
        serverDisksPage.actions.clickDiskSizeUpModalBtn()
        cy.wait(50000)
        serverAction_page.actions.clickServerActionsBtn()
        cy.wait(2000)
        serverAction_page.actions.clickStopServerBtn()
        cy.wait(2000)
        try {
            serverAction_page.actions.isServerStoppedStatus()
        } catch {
            cy.wait(30000)
            serverAction_page.actions.isServerStoppedStatus()
        }
        serverDisksPage.actions.isVisibleCreatedDisk(number)
    })
    it("[PD-675] Increase NVME disk automatically - With server reboot (math symbols)", () => {
        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        serverlist_page.actions.searchServer(configData.test_server_name)
        serverlist_page.actions.isVisibleSearchTxtServer(configData.test_server_name)
        serverlist_page.actions.clickServerCard(configData.test_server_name)
        serverlist_page.actions.isVisibleServerDetail(configData.test_server_name)
        serverDisksPage.actions.clickServerDisksTab()
        serverDisksPage.actions.clickNvmeIncreaseDiskSizeBtn()
        serverDisksPage.actions.clickWithServerRebootIncreaseDiskSizeBtn()
        serverDisksPage.actions.writeDiskSizeUpModalTxt('+')
        serverDisksPage.actions.isDisabledDiskSizeUpModalBtn()
    })
    it("[PD-676] Increase NVME disk automatically - With server reboot (more than max limit)", () => {
        const number = 10000;
        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        serverlist_page.actions.searchServer(configData.test_server_name)
        serverlist_page.actions.isVisibleSearchTxtServer(configData.test_server_name)
        serverlist_page.actions.clickServerCard(configData.test_server_name)
        serverlist_page.actions.isVisibleServerDetail(configData.test_server_name)
        serverDisksPage.actions.clickServerDisksTab()
        serverDisksPage.actions.clickNvmeIncreaseDiskSizeBtn()
        serverDisksPage.actions.clickWithServerRebootIncreaseDiskSizeBtn()
        serverDisksPage.actions.writeDiskSizeUpModalTxt(number)
        serverDisksPage.actions.clickDiskSizeUpModalBtn()
        serverDisksPage.actions.checkNewDiskSizeErrorLbl2("Максимальный размер диска 1000 Гб. Для расширения ограничения обратитесь в техническую поддержку Pro-Data")
    })
    it("[PD-677] Increase NVME disk automatically - With server reboot (0)", () => {
        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        serverlist_page.actions.searchServer(configData.test_server_name)
        serverlist_page.actions.isVisibleSearchTxtServer(configData.test_server_name)
        serverlist_page.actions.clickServerCard(configData.test_server_name)
        serverlist_page.actions.isVisibleServerDetail(configData.test_server_name)
        serverDisksPage.actions.clickServerDisksTab()
        serverDisksPage.actions.clickNvmeIncreaseDiskSizeBtn()
        serverDisksPage.actions.clickWithServerRebootIncreaseDiskSizeBtn()
        serverDisksPage.actions.writeDiskSizeUpModalTxt('0')
        serverDisksPage.actions.clickDiskSizeUpModalBtn()
        serverDisksPage.actions.checkNewDiskSizeErrorLbl2('Неверное значение')
    })
    it("[PD-696] Increase NVME disk size — X button", () => {
        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        serverlist_page.actions.searchServer(configData.test_server_name)
        serverlist_page.actions.isVisibleSearchTxtServer(configData.test_server_name)
        serverlist_page.actions.clickServerCard(configData.test_server_name)
        serverlist_page.actions.isVisibleServerDetail(configData.test_server_name)
        serverDisksPage.actions.clickServerDisksTab()
        serverDisksPage.actions.clickNvmeIncreaseDiskSizeBtn()
        serverDisksPage.actions.clickModalCloseBtn()
        serverDisksPage.actions.checkAddDiskBtnExists()
    })
    it("[PD-683] Mark NVME disk as bootable", () => {
        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        serverlist_page.actions.searchServer(configData.test_server_name)
        serverlist_page.actions.isVisibleSearchTxtServer(configData.test_server_name)
        serverlist_page.actions.clickServerCard(configData.test_server_name)
        serverlist_page.actions.isVisibleServerDetail(configData.test_server_name)
        serverDisksPage.actions.clickServerDisksTab()
        serverDisksPage.actions.clickNvmeDiskChangeToBootDiskBtn()
        serverDisksPage.actions.clickDiskmakeUploadConfirmBtn()
        cy.wait(2000)
        serverDisksPage.actions.checkNvmeDiskChangedToBootDisk()
    })
    it("[PD-686] Change NVME disk from boot disk", () => {
        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        serverlist_page.actions.searchServer(configData.test_server_name)
        serverlist_page.actions.isVisibleSearchTxtServer(configData.test_server_name)
        serverlist_page.actions.clickServerCard(configData.test_server_name)
        serverlist_page.actions.isVisibleServerDetail(configData.test_server_name)
        serverDisksPage.actions.clickServerDisksTab()
        serverDisksPage.actions.clickBootDiskChangeToBootDiskBtn()
        serverDisksPage.actions.clickDiskmakeUploadConfirmBtn()
        cy.wait(2000)
        serverDisksPage.actions.checkBootDiskChangedToBootDisk()
    })
    it("[PD-697] Mark NVME disk as bootable - Cancel button", () => {
        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        serverlist_page.actions.searchServer(configData.test_server_name)
        serverlist_page.actions.isVisibleSearchTxtServer(configData.test_server_name)
        serverlist_page.actions.clickServerCard(configData.test_server_name)
        serverlist_page.actions.isVisibleServerDetail(configData.test_server_name)
        serverDisksPage.actions.clickServerDisksTab()
        serverDisksPage.actions.clickNvmeDiskChangeToBootDiskBtn()
        serverDisksPage.actions.clickChangeToBootDiskModalCancelBtn()
        cy.wait(1000)
        serverDisksPage.actions.checkAddDiskBtnExists()
    })
    it("[PD-698] Detach NVME disk from VM - Cancel button", () => {
        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        serverlist_page.actions.searchServer(configData.test_server_name)
        serverlist_page.actions.isVisibleSearchTxtServer(configData.test_server_name)
        serverlist_page.actions.clickServerCard(configData.test_server_name)
        serverlist_page.actions.isVisibleServerDetail(configData.test_server_name)
        serverDisksPage.actions.clickServerDisksTab()
        serverDisksPage.actions.clickNvmeDiskDetachBtn()
        serverDisksPage.actions.clickNvmeDiskDetachModalCancelBtn()
        cy.wait(1000)
        serverDisksPage.actions.checkAddDiskBtnExists()
    })
    it("[PD-685] Detach NVME disk from VM", () => {
        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        serverlist_page.actions.searchServer(configData.test_server_name)
        serverlist_page.actions.isVisibleSearchTxtServer(configData.test_server_name)
        serverlist_page.actions.clickServerCard(configData.test_server_name)
        serverlist_page.actions.isVisibleServerDetail(configData.test_server_name)
        serverDisksPage.actions.clickServerDisksTab()
        serverDisksPage.actions.clickNvmeDiskDetachBtn()
        serverDisksPage.actions.clickDisconnectDiskModalBtn()
        cy.wait(3000)
        serverDisksPage.actions.checkNvmeDiskNotExists()
        sidebar.actions.clickDisksIcon()
        serverDisksPage.actions.checkNvmeDiskExists()
    })
    it("[PD-701] Connect NVME disk to BM - Close button", () => {
        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        serverlist_page.actions.searchServer(configData.test_server_name)
        serverlist_page.actions.isVisibleSearchTxtServer(configData.test_server_name)
        serverlist_page.actions.clickServerCard(configData.test_server_name)
        serverlist_page.actions.isVisibleServerDetail(configData.test_server_name)
        serverDisksPage.actions.clickServerDisksTab()
        serverDisksPage.actions.clickConnectNewServerDiskBtn()
        serverDisksPage.actions.clickModalCloseBtn()
        cy.wait(1000)
        serverDisksPage.actions.checkAddDiskBtnExists()
    })
    it("[PD-687] Connect NVME disk to VM", () => {
        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        serverlist_page.actions.searchServer(configData.test_server_name)
        serverlist_page.actions.isVisibleSearchTxtServer(configData.test_server_name)
        serverlist_page.actions.clickServerCard(configData.test_server_name)
        serverlist_page.actions.isVisibleServerDetail(configData.test_server_name)
        serverDisksPage.actions.clickServerDisksTab()
        serverDisksPage.actions.clickConnectNewServerDiskBtn()
        serverDisksPage.actions.clickConnectDiskSelector()
        serverDisksPage.actions.selectConnectNvmeDiskOption()
        serverDisksPage.actions.clickConnectDiskModalBtn()
        cy.wait(1000)
        serverDisksPage.actions.checkNvmeDiskExists()
    })
    it("[PD-700] Delete NVME disk from BM - Cancel button", () => {
        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        serverlist_page.actions.searchServer(configData.test_server_name)
        serverlist_page.actions.isVisibleSearchTxtServer(configData.test_server_name)
        serverlist_page.actions.clickServerCard(configData.test_server_name)
        serverlist_page.actions.isVisibleServerDetail(configData.test_server_name)
        serverDisksPage.actions.clickServerDisksTab()
        serverDisksPage.actions.clickNvmeDiskDeleteBtn()
        serverDisksPage.actions.clickNvmeDiskDeleteModalCancelBtn()
        cy.wait(1000)
        serverDisksPage.actions.checkAddDiskBtnExists()
    })
    it("[PD-688] Delete NVME disk from BM", () => {
        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        serverlist_page.actions.searchServer(configData.test_server_name)
        serverlist_page.actions.isVisibleSearchTxtServer(configData.test_server_name)
        serverlist_page.actions.clickServerCard(configData.test_server_name)
        serverlist_page.actions.isVisibleServerDetail(configData.test_server_name)
        serverDisksPage.actions.clickServerDisksTab()
        serverDisksPage.actions.clickNvmeDiskDeleteBtn()
        serverDisksPage.actions.clickConfDeleteBtn()
        cy.wait(1000)
        serverDisksPage.actions.checkNvmeDiskNotExists()
    })
})