cy.on('uncaught:exception', (err, runnable) => {
    return false;
});
import server_page from "../pages/server_page";
import sidebar from "../pages/sidebar";
import localNetworks_page from "../pages/local-networks_page";
import serverlist_page from "../pages/server-list_page";

describe('9.Servers - Local Network tab', () => {
    let configData;
    before(() => {
        cy.fixture('examples').then((data) => {
            configData = data;
        });
    })
    beforeEach(() => {
        cy.viewport(1280, 720)
        cy.intercept('POST', `${configData.base_url}panel-main/api/v1/auth/sign-in`).as('signInRequest');
        cy.intercept('GET', `${configData.base_url}panel-main/api/panel/vm/list`).as('serverStatusStopped3');
        cy.intercept('POST', `${configData.base_url}panel-main/api/panel/vm/${configData.test_server_id}/linkLocalNet`).as('networkSuccessAdd');
        cy.intercept('POST', `${configData.base_url}panel-main/api/panel/vm/${configData.test_server_id}/unlinkNet`).as('networkSuccessDelete');
        cy.intercept('POST', `${configData.base_url}panel-main/api/panel/vm/${configData.test_server_id}/nets/3351/edit`).as('networkIpEditSuccess');

    })
    it('Add local network (Without reboot)', () => {
        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        serverlist_page.actions.searchServer(configData.test_server_name)
        serverlist_page.actions.isVisibleSearchTxtServer(configData.test_server_name)
        serverlist_page.actions.clickServerCard(configData.test_server_name)
        serverlist_page.actions.isVisibleServerDetail(configData.test_server_name)
        localNetworks_page.actions.clickLocalNetworkTxt()
        localNetworks_page.actions.clickAddNetworkBtn()
        localNetworks_page.actions.isVisibleSelectListNetwork()
        localNetworks_page.actions.clickSelectListNetwork()
        localNetworks_page.actions.isVisibleNetworkIp('NTester')
        localNetworks_page.actions.clickNetworkIpBtn('NTester')
        localNetworks_page.actions.clickAddNetworkSuccessBtn()
        localNetworks_page.actions.isVisibleNetworkDetachBtn()
        localNetworks_page.actions.clickDetachNetworkBtn()
        localNetworks_page.actions.clickConfirmCheckbox()
        localNetworks_page.actions.clickNetworkDeleteConfirmBtn()
        cy.wait(3000) // we need to wait since deletion takes some time
        localNetworks_page.actions.isNotVisibleNetworkEditeBtn()
    })
    it('Add local network (With reboot)', () => {
        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        serverlist_page.actions.searchServer(configData.test_server_name)
        serverlist_page.actions.isVisibleSearchTxtServer(configData.test_server_name)
        serverlist_page.actions.clickServerCard(configData.test_server_name)
        serverlist_page.actions.isVisibleServerDetail(configData.test_server_name)
        localNetworks_page.actions.clickLocalNetworkTxt()
        localNetworks_page.actions.clickAddNetworkBtn()
        localNetworks_page.actions.clickNetworkWithRebootBtn()
        localNetworks_page.actions.isVisibleSelectListNetwork()
        localNetworks_page.actions.clickSelectListNetwork()
        localNetworks_page.actions.isVisibleNetworkIp('NTester')
        localNetworks_page.actions.clickNetworkIpBtn('NTester')
        localNetworks_page.actions.clickAddNetworkSuccessBtn()
        localNetworks_page.actions.isVisibleNetworkDetachBtn()
        localNetworks_page.actions.clickDetachNetworkBtn()
        localNetworks_page.actions.clickConfirmCheckbox()
        localNetworks_page.actions.clickNetworkDeleteConfirmBtn()
        cy.wait(3000) // we need to wait since deletion takes some time
        localNetworks_page.actions.isNotVisibleNetworkEditeBtn()
    })
    it('Add local network (Without IP)', () => {
        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        serverlist_page.actions.searchServer(configData.test_server_name)
        serverlist_page.actions.isVisibleSearchTxtServer(configData.test_server_name)
        serverlist_page.actions.clickServerCard(configData.test_server_name)
        serverlist_page.actions.isVisibleServerDetail(configData.test_server_name)        
        localNetworks_page.actions.clickLocalNetworkTxt()
        localNetworks_page.actions.clickAddNetworkBtn()

    })
    it('Add local network (With invalid IP)', () => {
        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        serverlist_page.actions.searchServer(configData.test_server_name)
        serverlist_page.actions.isVisibleSearchTxtServer(configData.test_server_name)
        serverlist_page.actions.clickServerCard(configData.test_server_name)
        serverlist_page.actions.isVisibleServerDetail(configData.test_server_name)
        localNetworks_page.actions.clickLocalNetworkTxt()
        localNetworks_page.actions.clickAddNetworkBtn()
        localNetworks_page.actions.clickNetworkWithRebootBtn()
        localNetworks_page.actions.isVisibleSelectListNetwork()
        localNetworks_page.actions.clickSelectListNetwork()
        localNetworks_page.actions.isVisibleNetworkIp('NTester')
        localNetworks_page.actions.clickNetworkIpBtn('NTester')
        localNetworks_page.actions.clickSelectServerIpAddress()
        localNetworks_page.actions.typeToSearchIpAddressField("100.293.223.28")
        localNetworks_page.actions.isVisibleServerIpNotFoundText("Ничего не найдено")
    })
    it('Add local network (Already exists- should not allow adding again)', () => {
        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        serverlist_page.actions.searchServer(configData.test_server_name)
        serverlist_page.actions.isVisibleSearchTxtServer(configData.test_server_name)
        serverlist_page.actions.clickServerCard(configData.test_server_name)
        serverlist_page.actions.isVisibleServerDetail(configData.test_server_name)
        localNetworks_page.actions.clickLocalNetworkTxt()
        localNetworks_page.actions.clickAddNetworkBtn()
        localNetworks_page.actions.isVisibleSelectListNetwork()
        localNetworks_page.actions.clickSelectListNetwork()
        localNetworks_page.actions.isVisibleNetworkIp('NTester')
        localNetworks_page.actions.clickNetworkIpBtn('NTester')
        localNetworks_page.actions.clickAddNetworkSuccessBtn()
        localNetworks_page.actions.isVisibleNetworkDetachBtn()
        localNetworks_page.actions.clickAddNetworkBtn()
        localNetworks_page.actions.isVisibleSelectListNetwork()
        localNetworks_page.actions.clickSelectListNetwork()
    })
    it('Change IP of existing network', () => {
        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        serverlist_page.actions.searchServer(configData.test_server_name)
        serverlist_page.actions.isVisibleSearchTxtServer(configData.test_server_name)
        serverlist_page.actions.clickServerCard(configData.test_server_name)
        serverlist_page.actions.isVisibleServerDetail(configData.test_server_name)
        localNetworks_page.actions.clickLocalNetworkTxt()
        localNetworks_page.actions.clickEditIpBtn()
        localNetworks_page.actions.isVisibleEditIpServerInp()
        localNetworks_page.actions.clickNetworkEditInpLbl1()
        cy.wait(2000) // to load dropdown with IPs
        localNetworks_page.actions.enterEditIpServerNetworkTxt2()
        localNetworks_page.actions.clickCheckboxVerifiedSuccessIp()
        localNetworks_page.actions.clickEditIpSavedBtn()
        localNetworks_page.actions.clickDetachNetworkBtn()
        localNetworks_page.actions.clickConfirmCheckbox()
        localNetworks_page.actions.clickNetworkDeleteConfirmBtn()
        localNetworks_page.actions.isNotVisibleNetworkEditeBtn()
    })
    it('Change IP (Without reboot confirmation)', () => {
        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        serverlist_page.actions.searchServer(configData.test_server_name)
        serverlist_page.actions.isVisibleSearchTxtServer(configData.test_server_name)
        serverlist_page.actions.clickServerCard(configData.test_server_name)
        serverlist_page.actions.isVisibleServerDetail(configData.test_server_name)
        localNetworks_page.actions.clickLocalNetworkTxt()
        localNetworks_page.actions.clickAddNetworkBtn()
        localNetworks_page.actions.clickNetworkWithRebootBtn()
        localNetworks_page.actions.isVisibleSelectListNetwork()
        localNetworks_page.actions.clickSelectListNetwork()
        localNetworks_page.actions.isVisibleNetworkIp('NTester')
        localNetworks_page.actions.clickNetworkIpBtn('NTester')
        localNetworks_page.actions.clickAddNetworkSuccessBtn()
        localNetworks_page.actions.clickEditIpBtn()
        localNetworks_page.actions.isVisibleEditIpServerInp()
        localNetworks_page.actions.clickNetworkEditInpLbl1()
        cy.wait(2000) // to load dropdown with IPs
        localNetworks_page.actions.enterEditIpServerNetworkTxt2()
        localNetworks_page.actions.clickEditIpSavedBtn()
        localNetworks_page.actions.clickDetachNetworkBtn()
        localNetworks_page.actions.clickConfirmCheckbox()
        localNetworks_page.actions.clickNetworkDeleteConfirmBtn()
        localNetworks_page.actions.isNotVisibleNetworkEditeBtn()

    })
    it('Detach network', () => {
        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        serverlist_page.actions.searchServer(configData.test_server_name)
        serverlist_page.actions.isVisibleSearchTxtServer(configData.test_server_name)
        serverlist_page.actions.clickServerCard(configData.test_server_name)
        serverlist_page.actions.isVisibleServerDetail(configData.test_server_name)
        localNetworks_page.actions.clickLocalNetworkTxt()
        localNetworks_page.actions.clickAddNetworkBtn()
        localNetworks_page.actions.clickNetworkWithRebootBtn()
        localNetworks_page.actions.isVisibleSelectListNetwork()
        localNetworks_page.actions.clickSelectListNetwork()
        localNetworks_page.actions.isVisibleNetworkIp('NTester')
        localNetworks_page.actions.clickNetworkIpBtn('NTester')
        localNetworks_page.actions.clickAddNetworkSuccessBtn()
        localNetworks_page.actions.isVisibleNetworkDetachBtn()
        localNetworks_page.actions.clickDetachNetworkBtn()
        localNetworks_page.actions.clickConfirmCheckbox()
        localNetworks_page.actions.clickNetworkDeleteConfirmBtn()
        localNetworks_page.actions.isNotVisibleNetworkEditeBtn()
    })
    it('Detach network (Without reboot confirmation). Status should remain in Running', () => {
        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        serverlist_page.actions.searchServer(configData.test_server_name)
        serverlist_page.actions.isVisibleSearchTxtServer(configData.test_server_name)
        serverlist_page.actions.clickServerCard(configData.test_server_name)
        serverlist_page.actions.isVisibleServerDetail(configData.test_server_name)
        localNetworks_page.actions.clickLocalNetworkTxt()
        localNetworks_page.actions.clickAddNetworkBtn()
        localNetworks_page.actions.isVisibleSelectListNetwork()
        localNetworks_page.actions.clickSelectListNetwork()
        localNetworks_page.actions.isVisibleNetworkIp('NTester')
        localNetworks_page.actions.clickNetworkIpBtn('NTester')
        localNetworks_page.actions.clickAddNetworkSuccessBtn()
        localNetworks_page.actions.isVisibleNetworkDetachBtn()
        localNetworks_page.actions.clickDetachNetworkBtn()
        localNetworks_page.actions.clickConfirmCheckbox()
        localNetworks_page.actions.clickNetworkDeleteConfirmBtn()
        localNetworks_page.actions.isNotVisibleNetworkEditeBtn()
    })
})
// Test-Server remains in Running status
