cy.on('uncaught:exception', (err, runnable) => {
    return false;
});
import server_page from "../pages/server_page";
import sidebar from "../pages/sidebar";
import localNetworks_page from "../pages/localNetworks_page";

describe('9.Servers - Local Network tab', () => {
    let configData;
    before(() => {
        cy.fixture('examples').then((data) => {
            configData = data;
        });
    })
    beforeEach(() => {
        cy.viewport(1280, 720)
        cy.intercept('POST', `${configData.base_url}panel-main/api/v1/auth/sign-in`).as('signInRequest');
        cy.intercept('GET', `${configData.base_url}panel-main/api/panel/vm/list`).as('serverStatusStopped3');
        cy.intercept('POST', `${configData.base_url}panel-main/api/panel/vm/${configData.test_server_id}/linkLocalNet`).as('networkSuccessAdd');
        cy.intercept('POST', `${configData.base_url}panel-main/api/panel/vm/${configData.test_server_id}/unlinkNet`).as('networkSuccessDelete');
        cy.intercept('POST', `${configData.base_url}panel-main/api/panel/vm/${configData.test_server_id}/nets/3351/edit`).as('networkIpEditSuccess');

    })
    it('Добавить сеть ( С перезагрузкой сервера )', () => {
        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        localNetworks_page.actions.checkServerStatusStopped3()
        localNetworks_page.actions.clickLocalNetworkTxt()
        localNetworks_page.actions.clickAddNetworkBtn()
        localNetworks_page.actions.isVisibleSelectListNetwork()
        localNetworks_page.actions.clickSelectListNetwork()
        localNetworks_page.actions.isVisibleNetworkIp('NTester')
        localNetworks_page.actions.clickNetworkIpBtn('NTester')
        cy.wait(1000)
        localNetworks_page.actions.clickAddNetworkSuccessBtn()
        //localNetworks_page.actions.networkSuccessAdded()
        localNetworks_page.actions.isVisibleNetworkDeleteBtn()
        cy.wait(3000)
        localNetworks_page.actions.clickDeleteNetworkBtn()
        localNetworks_page.actions.clickConfirmCheckbox()
        localNetworks_page.actions.clickNetworkDeleteConfirmBtn()
        cy.wait(3000)
        //localNetworks_page.actions.networkSuccessDeleted()
        cy.reload()
        localNetworks_page.actions.isNotVisibleNetworkEditeBtn()
    })
    it('Добавить сеть ( Без перезагрузки сервера)', () => {
        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        localNetworks_page.actions.checkServerStatusStopped3()
        localNetworks_page.actions.clickLocalNetworkTxt()
        localNetworks_page.actions.clickAddNetworkBtn()
        localNetworks_page.actions.clickNetworkWithoutRebootBtn()
        localNetworks_page.actions.isVisibleSelectListNetwork()
        localNetworks_page.actions.clickSelectListNetwork()
        localNetworks_page.actions.isVisibleNetworkIp('NTester')
        localNetworks_page.actions.clickNetworkIpBtn('NTester')
        cy.wait(1000)
        localNetworks_page.actions.clickAddNetworkSuccessBtn()
        cy.wait(2000)
        //localNetworks_page.actions.networkSuccessAdded()
        localNetworks_page.actions.isVisibleNetworkDeleteBtn()
        cy.wait(3000)
        localNetworks_page.actions.clickDeleteNetworkBtn()
        localNetworks_page.actions.clickConfirmCheckbox()
        localNetworks_page.actions.clickNetworkDeleteConfirmBtn()
        cy.wait(5000)
        //localNetworks_page.actions.networkSuccessDeleted()
        cy.reload()
        localNetworks_page.actions.isNotVisibleNetworkEditeBtn()
    })
    it('Добавить сеть (Без IP)', () => {
        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        localNetworks_page.actions.checkServerStatusStopped3()
        localNetworks_page.actions.clickLocalNetworkTxt()
        localNetworks_page.actions.clickAddNetworkBtn()
        cy.wait(1000)
        localNetworks_page.actions.clickAddNetworkSuccessBtn()
        localNetworks_page.actions.isVisibleInValidMessageServerIp()
    })
    it('Добавить сеть (С неправильным IP)', () => {
        // 
        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        localNetworks_page.actions.checkServerStatusStopped3()
        cy.wait(2000)
        localNetworks_page.actions.clickLocalNetworkTxt()
        localNetworks_page.actions.clickAddNetworkBtn()
        localNetworks_page.actions.clickNetworkWithoutRebootBtn()
        localNetworks_page.actions.isVisibleSelectListNetwork()
        localNetworks_page.actions.clickSelectListNetwork()
        localNetworks_page.actions.enterServerIpInp("100.293.223.28")
        cy.wait(1000)
        localNetworks_page.actions.clickAddNetworkSuccessBtn()
        localNetworks_page.actions.isVisibleInValidMessageServerIp()
    })
    it('Добавить уже имеющуюся сеть второй раз (не должно дать)', () => {
        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        localNetworks_page.actions.checkServerStatusStopped3()
        localNetworks_page.actions.clickLocalNetworkTxt()
        cy.wait(1000)
        localNetworks_page.actions.clickAddNetworkBtn()
        localNetworks_page.actions.isVisibleSelectListNetwork()
        localNetworks_page.actions.clickSelectListNetwork()
        localNetworks_page.actions.isVisibleNetworkIp('NTester')
        localNetworks_page.actions.clickNetworkIpBtn('NTester')
        cy.wait(1000)
        localNetworks_page.actions.clickAddNetworkSuccessBtn()
        cy.wait(2000)
        localNetworks_page.actions.isVisibleNetworkDeleteBtn()
        localNetworks_page.actions.clickLocalNetworkTxt()
        cy.wait(2000)
        localNetworks_page.actions.clickAddNetworkBtn()
        localNetworks_page.actions.isVisibleSelectListNetwork()
        localNetworks_page.actions.clickSelectListNetwork()
        // localNetworks_page.actions.isNotVisibleNetworkIpTxt()
        cy.wait(2000)
        // localNetworks_page.actions.clickSelectListNetwork()
        localNetworks_page.actions.clickClosedModalBtn1()
        cy.wait(1000)
        localNetworks_page.actions.isVisibleNetworkDeleteBtn()
        localNetworks_page.actions.clickDeleteNetworkBtn()
        localNetworks_page.actions.clickConfirmCheckbox()
        cy.wait(2000)
        localNetworks_page.actions.clickNetworkDeleteConfirmBtn()
        cy.wait(10000)
       // localNetworks_page.actions.networkSuccessDeleted()
        cy.wait(2000)
        localNetworks_page.actions.isNotVisibleNetworkEditeBtn()

    })
    it('Изменить IP у имеющейся сети', () => {
        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        localNetworks_page.actions.checkServerStatusStopped3()
        localNetworks_page.actions.clickLocalNetworkTxt()
        cy.wait(1000)
        localNetworks_page.actions.clickAddNetworkBtn()
        localNetworks_page.actions.clickNetworkWithoutRebootBtn()
        localNetworks_page.actions.isVisibleSelectListNetwork()
        localNetworks_page.actions.clickSelectListNetwork()
        localNetworks_page.actions.isVisibleNetworkIp('NTester')
        localNetworks_page.actions.clickNetworkIpBtn('NTester')
        cy.wait(1000)
        localNetworks_page.actions.clickAddNetworkSuccessBtn()
        //localNetworks_page.actions.networkSuccessAdded()
        cy.wait(2000)
        localNetworks_page.actions.isVisibleNetworkDeleteBtn()
        localNetworks_page.actions.clickEditIpBtn()
        localNetworks_page.actions.isVisibleEditIpServerInp()
        localNetworks_page.actions.clickNetworkEditInpLbl1()
        localNetworks_page.actions.enterEditIpServerNetworkTxt("192.168.12.0")
        localNetworks_page.actions.clickCheckboxVerifiedSuccessIp()
        localNetworks_page.actions.clickEditIpSavedBtn()
        cy.wait(1000)
        localNetworks_page.actions.clickDeleteNetworkBtn()
        localNetworks_page.actions.clickConfirmCheckbox()
        localNetworks_page.actions.clickNetworkDeleteConfirmBtn()
        cy.wait(3000)
        localNetworks_page.actions.isNotVisibleNetworkEditeBtn()
    })
    it('Изменить IP (Без подтверждения перезагрузки)', () => {
        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        localNetworks_page.actions.checkServerStatusStopped3()
        localNetworks_page.actions.clickLocalNetworkTxt()
        localNetworks_page.actions.clickAddNetworkBtn()
        localNetworks_page.actions.clickNetworkWithoutRebootBtn()
        localNetworks_page.actions.isVisibleSelectListNetwork()
        localNetworks_page.actions.clickSelectListNetwork()
        localNetworks_page.actions.isVisibleNetworkIp('NTester')
        localNetworks_page.actions.clickNetworkIpBtn('NTester')
        cy.wait(1000)
        localNetworks_page.actions.clickAddNetworkSuccessBtn()
        //localNetworks_page.actions.networkSuccessAdded()
        cy.wait(2000)
        localNetworks_page.actions.isVisibleNetworkDeleteBtn()
        localNetworks_page.actions.clickEditIpBtn()
        cy.wait(1000)
        localNetworks_page.actions.isVisibleEditIpServerInp()
        localNetworks_page.actions.enterEditIpServerNetworkTxt("192.168.1.10")
        localNetworks_page.actions.clickModalCloseTxtBtn()
        localNetworks_page.actions.clickEditIpSavedBtn()
        cy.wait(4000)
        localNetworks_page.actions.clickDeleteNetworkBtn()
        localNetworks_page.actions.clickConfirmCheckbox()
        localNetworks_page.actions.clickNetworkDeleteConfirmBtn()
        cy.wait(3000)
        localNetworks_page.actions.isNotVisibleNetworkEditeBtn()

    })
    it('Отвязать сеть', () => {
        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        localNetworks_page.actions.checkServerStatusStopped3()
        localNetworks_page.actions.clickLocalNetworkTxt()
        localNetworks_page.actions.clickAddNetworkBtn()
        localNetworks_page.actions.clickNetworkWithoutRebootBtn()
        localNetworks_page.actions.isVisibleSelectListNetwork()
        localNetworks_page.actions.clickSelectListNetwork()
        localNetworks_page.actions.isVisibleNetworkIp('NTester')
        localNetworks_page.actions.clickNetworkIpBtn('NTester')
        cy.wait(1000)
        localNetworks_page.actions.clickAddNetworkSuccessBtn()
        cy.wait(2000)
        //localNetworks_page.actions.networkSuccessAdded()
        localNetworks_page.actions.isVisibleNetworkDeleteBtn()
        cy.wait(3000)
        localNetworks_page.actions.clickDeleteNetworkBtn()
        localNetworks_page.actions.clickConfirmCheckbox()
        localNetworks_page.actions.clickNetworkDeleteConfirmBtn()
        cy.wait(3000)
        //localNetworks_page.actions.networkSuccessDeleted()
        cy.reload()
        localNetworks_page.actions.isNotVisibleNetworkEditeBtn()
    })
    it('Отвязать сеть (Без подтверждения перезагрузки). Статус должен остаться В работе', () => {
        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickServersIcon()
        server_page.actions.checkServerPageLbl()
        localNetworks_page.actions.checkServerStatusStopped3()
        localNetworks_page.actions.clickLocalNetworkTxt()
        localNetworks_page.actions.clickAddNetworkBtn()
        localNetworks_page.actions.isVisibleSelectListNetwork()
        localNetworks_page.actions.clickSelectListNetwork()
        localNetworks_page.actions.isVisibleNetworkIp('NTester')
        localNetworks_page.actions.clickNetworkIpBtn('NTester')
        cy.wait(1000)
        localNetworks_page.actions.clickAddNetworkSuccessBtn()
        cy.wait(2000)
        localNetworks_page.actions.isVisibleNetworkDeleteBtn()
        localNetworks_page.actions.clickDeleteNetworkBtn()
        cy.wait(4000)
        localNetworks_page.actions.clickConfirmCheckbox()
        cy.wait(2000)
        localNetworks_page.actions.clickNetworkDeleteConfirmBtn()
        cy.wait(6000)
        //localNetworks_page.actions.networkSuccessDeleted()
        localNetworks_page.actions.isNotVisibleNetworkEditeBtn()
    })
})