cy.on('uncaught:exception', (err, runnable) => {
    return false;
});

import action_history from "../pages/action_history_page";
import sidebar from "../pages/sidebar";

describe('27.Actions Logs Tests', () => {
    let configData;
    before(() => {
        cy.fixture('examples').then((data) => {
            configData = data;
        });
    })
    beforeEach(() => {
        cy.viewport(1280, 720)
        cy.intercept('POST', `${configData.base_url}panel-main/api/v1/auth/sign-in`).as('signInRequest');
    })
    it('[PD-253] Поиск по логин', () => {
        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickUserCredentials()
        sidebar.actions.clickAction_history_icon()
        cy.wait(3000)
        action_history.actions.typeActoon_searchTxt(configData.login)
        action_history.actions.isVisibleFoundLog(configData.login)
    })
    it('[PD-254] Поиск по ИП', () => {
        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickUserCredentials()
        sidebar.actions.clickAction_history_icon()
        cy.wait(3000)
        action_history.actions.typeActoon_searchTxt(configData.user_ip)
        action_history.actions.isVisibleFoundLog(configData.user_ip)
    })
    it('[PD-255] Выбрать только сегодня (период)', () => {
        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickUserCredentials()
        sidebar.actions.clickAction_history_icon()
        cy.wait(3000)
        action_history.actions.clickFilterByDateBtn()
        action_history.actions.doubleClickSelectTodayBtn()
        action_history.actions.clickApplyDateFilterBtn()
        action_history.actions.clickApplyFilterBtn()
        cy.wait(2000)
        action_history.actions.isVisibleFoundLog(configData.login)
        action_history.actions.isVisibleFoundLog(configData.user_ip)
    })
    it('[PD-256] Выбрать один день (Вчера или ещё раннее)', () => {
        cy.login(configData.base_url, configData.login, configData.password)
        sidebar.actions.clickUserCredentials()
        sidebar.actions.clickAction_history_icon()
        cy.wait(3000)
        action_history.actions.clickFilterByDateBtn()
        action_history.actions.doubleClickSelectYesterdayBtn()
        action_history.actions.clickApplyDateFilterBtn()
        action_history.actions.clickApplyFilterBtn()
        cy.wait(2000)
        action_history.actions.isVisibleFoundLog(configData.login)
        action_history.actions.isVisibleFoundLog(configData.user_ip)
    })
    it('[PD-257] Выбрать тип действия: Добавлен диск', () => {
        cy.login(configData.base_url, configData.login, configData.password)

        sidebar.actions.clickUserCredentials()
        sidebar.actions.clickAction_history_icon()
        cy.wait(3000)
        action_history.actions.clickActionTypeSelectBtn()
        action_history.actions.selectActionTypeOption('Добавлен диск')
        action_history.actions.clickApplyFilterBtn()
        cy.wait(2000)
        action_history.actions.isVisibleFoundLog("Добавлен диск")
    })
    it('[PD-258] Выбрать тип действия: Запуск ВМ', () => {
        cy.login(configData.base_url, configData.login, configData.password)

        sidebar.actions.clickUserCredentials()
        sidebar.actions.clickAction_history_icon()
        cy.wait(3000)
        action_history.actions.clickActionTypeSelectBtn()
        action_history.actions.selectActionTypeOption('Запуск ВМ')
        action_history.actions.clickApplyFilterBtn()
        cy.wait(2000)
        action_history.actions.isVisibleFoundLog("Запуск ВМ")
    })
    it('[PD-259] Выбрать тип действия: Остановка ВМ', () => {
        cy.login(configData.base_url, configData.login, configData.password)

        sidebar.actions.clickUserCredentials()
        sidebar.actions.clickAction_history_icon()
        cy.wait(3000)
        action_history.actions.clickActionTypeSelectBtn()
        action_history.actions.selectActionTypeOption('Остановка ВМ')
        action_history.actions.clickApplyFilterBtn()
        cy.wait(2000)
        action_history.actions.isVisibleFoundLog("Остановка ВМ")
    })
    it('[PD-260] Выбрать тип действия: Отключить ВМ', () => {
        cy.login(configData.base_url, configData.login, configData.password)

        sidebar.actions.clickUserCredentials()
        sidebar.actions.clickAction_history_icon()
        cy.wait(3000)
        action_history.actions.clickActionTypeSelectBtn()
        action_history.actions.selectActionTypeOption('Отключить ВМ')
        action_history.actions.clickApplyFilterBtn()
        cy.wait(2000)
        action_history.actions.isVisibleFoundLog("Отключить ВМ")
    })
    it('[PD-261] Выбрать тип действия: Перезагрузка ВМ', () => {
        cy.login(configData.base_url, configData.login, configData.password)

        sidebar.actions.clickUserCredentials()
        sidebar.actions.clickAction_history_icon()
        cy.wait(3000)
        action_history.actions.clickActionTypeSelectBtn()
        action_history.actions.selectActionTypeOption('Перезагрузка ВМ')
        action_history.actions.clickApplyFilterBtn()
        cy.wait(2000)
        action_history.actions.isVisibleFoundLog("Перезагрузка ВМ")
    })
    it('[PD-262] Выбрать тип действия: Пользователь заблокирован', () => {
        cy.login(configData.base_url, configData.login, configData.password)

        sidebar.actions.clickUserCredentials()
        sidebar.actions.clickAction_history_icon()
        cy.wait(3000)
        action_history.actions.clickActionTypeSelectBtn()
        action_history.actions.selectActionTypeOption('Пользователь заблокирован')
        action_history.actions.clickApplyFilterBtn()
        cy.wait(2000)
        action_history.actions.isVisibleFoundLog("Пользователь заблокирован")
    })
    it('[PD-263] Выбрать тип действия: Пользователь разблокирован', () => {
        cy.login(configData.base_url, configData.login, configData.password)

        sidebar.actions.clickUserCredentials()
        sidebar.actions.clickAction_history_icon()
        cy.wait(3000)
        action_history.actions.clickActionTypeSelectBtn()
        action_history.actions.selectActionTypeOption('Пользователь разблокирован')
        action_history.actions.clickApplyFilterBtn()
        cy.wait(2000)
        action_history.actions.isVisibleFoundLog("Пользователь разблокирован")
    })
    it('[PD-264] Выбрать тип действия: Попытка авторизации', () => {
        cy.login(configData.base_url, configData.login, configData.password)

        sidebar.actions.clickUserCredentials()
        sidebar.actions.clickAction_history_icon()
        cy.wait(3000)
        action_history.actions.clickActionTypeSelectBtn()
        action_history.actions.selectActionTypeOption('Попытка авторизации')
        action_history.actions.clickApplyFilterBtn()
        cy.wait(2000)
        action_history.actions.isVisibleFoundLog("Неуспешная попытка входа")
    })
    it('[PD-265] Выбрать тип действия: Создан бэкап', () => {
        cy.login(configData.base_url, configData.login, configData.password)

        sidebar.actions.clickUserCredentials()
        sidebar.actions.clickAction_history_icon()
        cy.wait(3000)
        action_history.actions.clickActionTypeSelectBtn()
        action_history.actions.selectActionTypeOption('Создан бэкап')
        action_history.actions.clickApplyFilterBtn()
        cy.wait(2000)
        action_history.actions.isVisibleFoundLog("Создан бэкап")
    })
    it('[PD-266] Выбрать тип действия: Создан глобальный диск', () => {
        cy.login(configData.base_url, configData.login, configData.password)

        sidebar.actions.clickUserCredentials()
        sidebar.actions.clickAction_history_icon()
        cy.wait(3000)
        action_history.actions.clickActionTypeSelectBtn()
        action_history.actions.selectActionTypeOption('Создан глобальный диск')
        action_history.actions.clickApplyFilterBtn()
        cy.wait(2000)
        action_history.actions.isVisibleFoundLog("Создан глобальный диск")
    })
    it('[PD-267] Выбрать тип действия: Создана ВМ', () => {
        cy.login(configData.base_url, configData.login, configData.password)

        sidebar.actions.clickUserCredentials()
        sidebar.actions.clickAction_history_icon()
        cy.wait(3000)
        action_history.actions.clickActionTypeSelectBtn()
        action_history.actions.selectActionTypeOption('Создана ВМ')
        action_history.actions.clickApplyFilterBtn()
        cy.wait(2000)
        action_history.actions.isVisibleFoundLog("Создана ВМ")
    })
    it('[PD-268] Выбрать тип действия: Создана локальная сеть', () => {
        cy.login(configData.base_url, configData.login, configData.password)

        sidebar.actions.clickUserCredentials()
        sidebar.actions.clickAction_history_icon()
        cy.wait(3000)
        action_history.actions.clickActionTypeSelectBtn()
        action_history.actions.selectActionTypeOption('Создана локальная сеть')
        action_history.actions.clickApplyFilterBtn()
        cy.wait(2000)
        action_history.actions.isVisibleFoundLog("Создана локальная сеть")
    })
    it('[PD-269] Выбрать тип действия: Создание Local Load Balancer', () => {
        cy.login(configData.base_url, configData.login, configData.password)

        sidebar.actions.clickUserCredentials()
        sidebar.actions.clickAction_history_icon()
        cy.wait(3000)
        action_history.actions.clickActionTypeSelectBtn()
        action_history.actions.selectActionTypeOption('Создание Local Load Balancer')
        action_history.actions.clickApplyFilterBtn()
        cy.wait(2000)
        action_history.actions.isVisibleFoundLog("Создание Local Load Balancer")
    })
    it('[PD-270] Выбрать тип действия: Создание Public Load Balancer', () => {
        cy.login(configData.base_url, configData.login, configData.password)

        sidebar.actions.clickUserCredentials()
        sidebar.actions.clickAction_history_icon()
        cy.wait(3000)
        action_history.actions.clickActionTypeSelectBtn()
        action_history.actions.selectActionTypeOption('Создание Public Load Balancer')
        action_history.actions.clickApplyFilterBtn()
        cy.wait(2000)
        action_history.actions.isVisibleFoundLog("Создание Public Load Balancer")
    })
    it('[PD-271] Выбрать тип действия: Создание пользователя панели', () => {
        cy.login(configData.base_url, configData.login, configData.password)

        sidebar.actions.clickUserCredentials()
        sidebar.actions.clickAction_history_icon()
        cy.wait(3000)
        action_history.actions.clickActionTypeSelectBtn()
        action_history.actions.selectActionTypeOption('Создание пользователя панели')
        action_history.actions.clickApplyFilterBtn()
        cy.wait(2000)
        action_history.actions.isVisibleFoundLog("Создание пользователя панели")
    })
    it('[PD-272] Выбрать тип действия: Увеличен размер диска', () => {
        cy.login(configData.base_url, configData.login, configData.password)

        sidebar.actions.clickUserCredentials()
        sidebar.actions.clickAction_history_icon()
        cy.wait(3000)
        action_history.actions.clickActionTypeSelectBtn()
        action_history.actions.selectActionTypeOption('Увеличен размер диска')
        action_history.actions.clickApplyFilterBtn()
        cy.wait(2000)
        action_history.actions.isVisibleFoundLog("Увеличен размер диска")
    })
    it('[PD-273] Выбрать тип действия: Удалена ВМ', () => {
        cy.login(configData.base_url, configData.login, configData.password)

        sidebar.actions.clickUserCredentials()
        sidebar.actions.clickAction_history_icon()
        cy.wait(3000)
        action_history.actions.clickActionTypeSelectBtn()
        action_history.actions.selectActionTypeOption('Удалена ВМ')
        action_history.actions.clickApplyFilterBtn()
        cy.wait(2000)
        action_history.actions.isVisibleFoundLog("Удалена ВМ")
    })
    it('[PD-274] Выбрать тип действия: Удалена локальная сеть', () => {
        cy.login(configData.base_url, configData.login, configData.password)

        sidebar.actions.clickUserCredentials()
        sidebar.actions.clickAction_history_icon()
        cy.wait(3000)
        action_history.actions.clickActionTypeSelectBtn()
        action_history.actions.selectActionTypeOption('Удалена локальная сеть')
        action_history.actions.clickApplyFilterBtn()
        cy.wait(2000)
        action_history.actions.isVisibleFoundLog("Удалена локальная сеть")
    })
    it('[PD-275] Выбрать тип действия: Удалён бэкап', () => {
        cy.login(configData.base_url, configData.login, configData.password)

        sidebar.actions.clickUserCredentials()
        sidebar.actions.clickAction_history_icon()
        cy.wait(3000)
        action_history.actions.clickActionTypeSelectBtn()
        action_history.actions.selectActionTypeOption('Удалён бэкап')
        action_history.actions.clickApplyFilterBtn()
        cy.wait(2000)
        action_history.actions.isVisibleFoundLog("Удалён бэкап")
    })
    it('[PD-276] Выбрать тип действия: Удалён глобальный диск', () => {
        cy.login(configData.base_url, configData.login, configData.password)

        sidebar.actions.clickUserCredentials()
        sidebar.actions.clickAction_history_icon()
        cy.wait(3000)
        action_history.actions.clickActionTypeSelectBtn()
        action_history.actions.selectActionTypeOption('Удалён глобальный диск')
        action_history.actions.clickApplyFilterBtn()
        cy.wait(2000)
        action_history.actions.isVisibleFoundLog("Удалён глобальный диск")
    })
    it('[PD-277] Выбрать тип действия: Удалён диск', () => {
        cy.login(configData.base_url, configData.login, configData.password)

        sidebar.actions.clickUserCredentials()
        sidebar.actions.clickAction_history_icon()
        cy.wait(3000)
        action_history.actions.clickActionTypeSelectBtn()
        action_history.actions.selectActionTypeOption('Удалён диск')
        action_history.actions.clickApplyFilterBtn()
        cy.wait(2000)
        action_history.actions.isVisibleFoundLog("Удалён диск")
    })
    it('[PD-278] Выбрать тип действия: Удалён публичный IP', () => {
        cy.login(configData.base_url, configData.login, configData.password)

        sidebar.actions.clickUserCredentials()
        sidebar.actions.clickAction_history_icon()
        cy.wait(3000)
        action_history.actions.clickActionTypeSelectBtn()
        action_history.actions.selectActionTypeOption('Удалён публичный IP')
        action_history.actions.clickApplyFilterBtn()
        cy.wait(2000)
        action_history.actions.isVisibleFoundLog("Удалён публичный IP")
    })
    it('[PD-279] Выбрать тип действия: Успешная авторизация', () => {
        cy.login(configData.base_url, configData.login, configData.password)

        sidebar.actions.clickUserCredentials()
        sidebar.actions.clickAction_history_icon()
        cy.wait(3000)
        action_history.actions.clickActionTypeSelectBtn()
        action_history.actions.selectActionTypeOption('Успешная авторизация')
        action_history.actions.clickApplyFilterBtn()
        cy.wait(2000)
        action_history.actions.isVisibleFoundLog("Успешная авторизация")
    })
})